// Code generated by hostcontractgen. DO NOT EDIT.
package registration

import "github.com/dayvidpham/pasture/internal/lifecycle/model"

const (
	EventSessionStart model.ContractEventKind = iota + 1
	EventSetup
	EventSessionEnd
	EventUserPromptSubmit
	EventUserPromptExpansion
	EventStop
	EventStopFailure
	EventPreToolUse
	EventPermissionRequest
	EventPermissionDenied
	EventPostToolUse
	EventPostToolUseFailure
	EventPostToolBatch
	EventFileChanged
	EventCwdChanged
	EventConfigChange
	EventInstructionsLoaded
	EventWorktreeCreate
	EventWorktreeRemove
	EventSubagentStart
	EventSubagentStop
	EventTeammateIdle
	EventTaskCreated
	EventTaskCompleted
	EventPreCompact
	EventPostCompact
	EventNotification
	EventMessageDisplay
	EventElicitation
	EventElicitationResult
)

const (
	FieldSessionID model.NativeFieldID = iota + 1
	FieldTranscriptPath
	FieldCWD
	FieldPermissionMode
	FieldHookEventName
	FieldEffort
	FieldAgentID
	FieldAgentType
	FieldSource
	FieldModel
	FieldSessionTitle
	FieldTrigger
	FieldReason
	FieldPrompt
	FieldCommandName
	FieldStopHookActive
	FieldError
	FieldErrorType
	FieldToolName
	FieldToolInput
	FieldToolUseID
	FieldRequestID
	FieldToolOutput
	FieldBatchResults
	FieldFilePath
	FieldConfigSource
	FieldMemoryType
	FieldLoadReason
	FieldGlobs
	FieldTriggerFilePath
	FieldParentFilePath
	FieldAgentTranscriptPath
	FieldTeammateName
	FieldTaskID
	FieldMessage
	FieldNotificationType
	FieldTitle
	FieldContent
	FieldFields
	FieldMCPServerName
	FieldResponse
)
