// Code generated by hostcontractgen. DO NOT EDIT.
package registration

import (
	"github.com/dayvidpham/pasture/internal/codegen/ir"
	"github.com/dayvidpham/pasture/internal/lifecycle/model"
)

func OpenCode1_18_10() Manifest {
	events := []Event{
		{Kind: EventOpenCodeCommandExecuted, NativeName: "command.executed", AllowedFields: []model.NativeFieldID{}, Identities: []Identity{}, Blocking: NonBlocking, Mutation: MutationNone, Failure: FailureReportAndContinue, StopLoop: StopLoopNotApplicable},
		{Kind: EventOpenCodeFileEdited, NativeName: "file.edited", AllowedFields: []model.NativeFieldID{}, Identities: []Identity{}, Blocking: NonBlocking, Mutation: MutationNone, Failure: FailureReportAndContinue, StopLoop: StopLoopNotApplicable},
		{Kind: EventOpenCodeFileWatcherUpdated, NativeName: "file.watcher.updated", AllowedFields: []model.NativeFieldID{}, Identities: []Identity{}, Blocking: NonBlocking, Mutation: MutationNone, Failure: FailureReportAndContinue, StopLoop: StopLoopNotApplicable},
		{Kind: EventOpenCodeInstallationUpdated, NativeName: "installation.updated", AllowedFields: []model.NativeFieldID{}, Identities: []Identity{}, Blocking: NonBlocking, Mutation: MutationNone, Failure: FailureReportAndContinue, StopLoop: StopLoopNotApplicable},
		{Kind: EventOpenCodeInstallationUpdate_available, NativeName: "installation.update_available", AllowedFields: []model.NativeFieldID{}, Identities: []Identity{}, Blocking: NonBlocking, Mutation: MutationNone, Failure: FailureReportAndContinue, StopLoop: StopLoopNotApplicable},
		{Kind: EventOpenCodeLspClientDiagnostics, NativeName: "lsp.client.diagnostics", AllowedFields: []model.NativeFieldID{}, Identities: []Identity{}, Blocking: NonBlocking, Mutation: MutationNone, Failure: FailureReportAndContinue, StopLoop: StopLoopNotApplicable},
		{Kind: EventOpenCodeLspUpdated, NativeName: "lsp.updated", AllowedFields: []model.NativeFieldID{}, Identities: []Identity{}, Blocking: NonBlocking, Mutation: MutationNone, Failure: FailureReportAndContinue, StopLoop: StopLoopNotApplicable},
		{Kind: EventOpenCodeMessageUpdated, NativeName: "message.updated", AllowedFields: []model.NativeFieldID{}, Identities: []Identity{}, Blocking: NonBlocking, Mutation: MutationNone, Failure: FailureReportAndContinue, StopLoop: StopLoopNotApplicable},
		{Kind: EventOpenCodeMessageRemoved, NativeName: "message.removed", AllowedFields: []model.NativeFieldID{}, Identities: []Identity{}, Blocking: NonBlocking, Mutation: MutationNone, Failure: FailureReportAndContinue, StopLoop: StopLoopNotApplicable},
		{Kind: EventOpenCodeMessagePartUpdated, NativeName: "message.part.updated", AllowedFields: []model.NativeFieldID{}, Identities: []Identity{}, Blocking: NonBlocking, Mutation: MutationNone, Failure: FailureReportAndContinue, StopLoop: StopLoopNotApplicable},
		{Kind: EventOpenCodeMessagePartRemoved, NativeName: "message.part.removed", AllowedFields: []model.NativeFieldID{}, Identities: []Identity{}, Blocking: NonBlocking, Mutation: MutationNone, Failure: FailureReportAndContinue, StopLoop: StopLoopNotApplicable},
		{Kind: EventOpenCodePermissionUpdated, NativeName: "permission.updated", AllowedFields: []model.NativeFieldID{}, Identities: []Identity{}, Blocking: NonBlocking, Mutation: MutationNone, Failure: FailureReportAndContinue, StopLoop: StopLoopNotApplicable},
		{Kind: EventOpenCodePermissionReplied, NativeName: "permission.replied", AllowedFields: []model.NativeFieldID{}, Identities: []Identity{}, Blocking: NonBlocking, Mutation: MutationNone, Failure: FailureReportAndContinue, StopLoop: StopLoopNotApplicable},
		{Kind: EventOpenCodeServerConnected, NativeName: "server.connected", AllowedFields: []model.NativeFieldID{}, Identities: []Identity{}, Blocking: NonBlocking, Mutation: MutationNone, Failure: FailureReportAndContinue, StopLoop: StopLoopNotApplicable},
		{Kind: EventOpenCodeServerInstanceDisposed, NativeName: "server.instance.disposed", AllowedFields: []model.NativeFieldID{}, Identities: []Identity{}, Blocking: NonBlocking, Mutation: MutationNone, Failure: FailureReportAndContinue, StopLoop: StopLoopNotApplicable},
		{Kind: EventOpenCodeSessionCreated, NativeName: "session.created", AllowedFields: []model.NativeFieldID{FieldOpenCodeSessionID}, Identities: []Identity{{Field: FieldOpenCodeSessionID, Binding: model.BindingSession, Required: true}}, Blocking: NonBlocking, Mutation: MutationNone, Failure: FailureReportAndContinue, StopLoop: StopLoopNotApplicable},
		{Kind: EventOpenCodeSessionUpdated, NativeName: "session.updated", AllowedFields: []model.NativeFieldID{}, Identities: []Identity{}, Blocking: NonBlocking, Mutation: MutationNone, Failure: FailureReportAndContinue, StopLoop: StopLoopNotApplicable},
		{Kind: EventOpenCodeSessionDeleted, NativeName: "session.deleted", AllowedFields: []model.NativeFieldID{}, Identities: []Identity{}, Blocking: NonBlocking, Mutation: MutationNone, Failure: FailureReportAndContinue, StopLoop: StopLoopNotApplicable},
		{Kind: EventOpenCodeSessionCompacted, NativeName: "session.compacted", AllowedFields: []model.NativeFieldID{}, Identities: []Identity{}, Blocking: NonBlocking, Mutation: MutationNone, Failure: FailureReportAndContinue, StopLoop: StopLoopNotApplicable},
		{Kind: EventOpenCodeSessionDiff, NativeName: "session.diff", AllowedFields: []model.NativeFieldID{}, Identities: []Identity{}, Blocking: NonBlocking, Mutation: MutationNone, Failure: FailureReportAndContinue, StopLoop: StopLoopNotApplicable},
		{Kind: EventOpenCodeSessionError, NativeName: "session.error", AllowedFields: []model.NativeFieldID{}, Identities: []Identity{}, Blocking: NonBlocking, Mutation: MutationNone, Failure: FailureReportAndContinue, StopLoop: StopLoopNotApplicable},
		{Kind: EventOpenCodeSessionIdle, NativeName: "session.idle", AllowedFields: []model.NativeFieldID{}, Identities: []Identity{}, Blocking: NonBlocking, Mutation: MutationNone, Failure: FailureReportAndContinue, StopLoop: StopLoopNotApplicable},
		{Kind: EventOpenCodeSessionStatus, NativeName: "session.status", AllowedFields: []model.NativeFieldID{}, Identities: []Identity{}, Blocking: NonBlocking, Mutation: MutationNone, Failure: FailureReportAndContinue, StopLoop: StopLoopNotApplicable},
		{Kind: EventOpenCodeTodoUpdated, NativeName: "todo.updated", AllowedFields: []model.NativeFieldID{}, Identities: []Identity{}, Blocking: NonBlocking, Mutation: MutationNone, Failure: FailureReportAndContinue, StopLoop: StopLoopNotApplicable},
		{Kind: EventOpenCodeTuiPromptAppend, NativeName: "tui.prompt.append", AllowedFields: []model.NativeFieldID{}, Identities: []Identity{}, Blocking: NonBlocking, Mutation: MutationNone, Failure: FailureReportAndContinue, StopLoop: StopLoopNotApplicable},
		{Kind: EventOpenCodeTuiCommandExecute, NativeName: "tui.command.execute", AllowedFields: []model.NativeFieldID{}, Identities: []Identity{}, Blocking: NonBlocking, Mutation: MutationNone, Failure: FailureReportAndContinue, StopLoop: StopLoopNotApplicable},
		{Kind: EventOpenCodeTuiToastShow, NativeName: "tui.toast.show", AllowedFields: []model.NativeFieldID{}, Identities: []Identity{}, Blocking: NonBlocking, Mutation: MutationNone, Failure: FailureReportAndContinue, StopLoop: StopLoopNotApplicable},
		{Kind: EventOpenCodePtyCreated, NativeName: "pty.created", AllowedFields: []model.NativeFieldID{}, Identities: []Identity{}, Blocking: NonBlocking, Mutation: MutationNone, Failure: FailureReportAndContinue, StopLoop: StopLoopNotApplicable},
		{Kind: EventOpenCodePtyUpdated, NativeName: "pty.updated", AllowedFields: []model.NativeFieldID{}, Identities: []Identity{}, Blocking: NonBlocking, Mutation: MutationNone, Failure: FailureReportAndContinue, StopLoop: StopLoopNotApplicable},
		{Kind: EventOpenCodePtyExited, NativeName: "pty.exited", AllowedFields: []model.NativeFieldID{}, Identities: []Identity{}, Blocking: NonBlocking, Mutation: MutationNone, Failure: FailureReportAndContinue, StopLoop: StopLoopNotApplicable},
		{Kind: EventOpenCodePtyDeleted, NativeName: "pty.deleted", AllowedFields: []model.NativeFieldID{}, Identities: []Identity{}, Blocking: NonBlocking, Mutation: MutationNone, Failure: FailureReportAndContinue, StopLoop: StopLoopNotApplicable},
		{Kind: EventOpenCodeVcsBranchUpdated, NativeName: "vcs.branch.updated", AllowedFields: []model.NativeFieldID{}, Identities: []Identity{}, Blocking: NonBlocking, Mutation: MutationNone, Failure: FailureReportAndContinue, StopLoop: StopLoopNotApplicable},
		{Kind: EventOpenCodeChatMessage, NativeName: "chat.message", AllowedFields: []model.NativeFieldID{}, Identities: []Identity{}, Blocking: Blocking, Mutation: MutationNone, Failure: FailureExitTwoBlocks, StopLoop: StopLoopNotApplicable},
		{Kind: EventOpenCodeChatParams, NativeName: "chat.params", AllowedFields: []model.NativeFieldID{}, Identities: []Identity{}, Blocking: Blocking, Mutation: MutationNone, Failure: FailureExitTwoBlocks, StopLoop: StopLoopNotApplicable},
		{Kind: EventOpenCodeChatHeaders, NativeName: "chat.headers", AllowedFields: []model.NativeFieldID{}, Identities: []Identity{}, Blocking: Blocking, Mutation: MutationNone, Failure: FailureExitTwoBlocks, StopLoop: StopLoopNotApplicable},
		{Kind: EventOpenCodePermissionAsk, NativeName: "permission.ask", AllowedFields: []model.NativeFieldID{}, Identities: []Identity{}, Blocking: Blocking, Mutation: MutationNone, Failure: FailureExitTwoBlocks, StopLoop: StopLoopNotApplicable},
		{Kind: EventOpenCodeCommandExecuteBefore, NativeName: "command.execute.before", AllowedFields: []model.NativeFieldID{}, Identities: []Identity{}, Blocking: Blocking, Mutation: MutationNone, Failure: FailureExitTwoBlocks, StopLoop: StopLoopNotApplicable},
		{Kind: EventOpenCodeToolExecuteBefore, NativeName: "tool.execute.before", AllowedFields: []model.NativeFieldID{FieldOpenCodeSessionID, FieldOpenCodeCallID}, Identities: []Identity{{Field: FieldOpenCodeSessionID, Binding: model.BindingSession, Required: true}, {Field: FieldOpenCodeCallID, Binding: model.BindingToolCall, Required: true}}, Blocking: Blocking, Mutation: MutationNone, Failure: FailureExitTwoBlocks, StopLoop: StopLoopNotApplicable},
		{Kind: EventOpenCodeShellEnv, NativeName: "shell.env", AllowedFields: []model.NativeFieldID{}, Identities: []Identity{}, Blocking: Blocking, Mutation: MutationNone, Failure: FailureExitTwoBlocks, StopLoop: StopLoopNotApplicable},
		{Kind: EventOpenCodeToolExecuteAfter, NativeName: "tool.execute.after", AllowedFields: []model.NativeFieldID{}, Identities: []Identity{}, Blocking: Blocking, Mutation: MutationNone, Failure: FailureExitTwoBlocks, StopLoop: StopLoopNotApplicable},
		{Kind: EventOpenCodeExperimentalChatMessagesTransform, NativeName: "experimental.chat.messages.transform", AllowedFields: []model.NativeFieldID{}, Identities: []Identity{}, Blocking: Blocking, Mutation: MutationNone, Failure: FailureExitTwoBlocks, StopLoop: StopLoopNotApplicable},
		{Kind: EventOpenCodeExperimentalChatSystemTransform, NativeName: "experimental.chat.system.transform", AllowedFields: []model.NativeFieldID{}, Identities: []Identity{}, Blocking: Blocking, Mutation: MutationNone, Failure: FailureExitTwoBlocks, StopLoop: StopLoopNotApplicable},
		{Kind: EventOpenCodeExperimentalProviderSmall_model, NativeName: "experimental.provider.small_model", AllowedFields: []model.NativeFieldID{}, Identities: []Identity{}, Blocking: Blocking, Mutation: MutationNone, Failure: FailureExitTwoBlocks, StopLoop: StopLoopNotApplicable},
		{Kind: EventOpenCodeExperimentalSessionCompacting, NativeName: "experimental.session.compacting", AllowedFields: []model.NativeFieldID{}, Identities: []Identity{}, Blocking: Blocking, Mutation: MutationNone, Failure: FailureExitTwoBlocks, StopLoop: StopLoopNotApplicable},
		{Kind: EventOpenCodeExperimentalCompactionAutocontinue, NativeName: "experimental.compaction.autocontinue", AllowedFields: []model.NativeFieldID{}, Identities: []Identity{}, Blocking: Blocking, Mutation: MutationNone, Failure: FailureExitTwoBlocks, StopLoop: StopLoopNotApplicable},
		{Kind: EventOpenCodeExperimentalTextComplete, NativeName: "experimental.text.complete", AllowedFields: []model.NativeFieldID{}, Identities: []Identity{}, Blocking: Blocking, Mutation: MutationNone, Failure: FailureExitTwoBlocks, StopLoop: StopLoopNotApplicable},
		{Kind: EventOpenCodeToolDefinition, NativeName: "tool.definition", AllowedFields: []model.NativeFieldID{}, Identities: []Identity{}, Blocking: Blocking, Mutation: MutationNone, Failure: FailureExitTwoBlocks, StopLoop: StopLoopNotApplicable},
	}
	contract, err := ir.NewRuntimeContractID(ir.HarnessOpenCode, "1.18.10")
	if err != nil {
		panic(err)
	}
	return Manifest{Harness: ir.HarnessOpenCode, Version: "1.18.10", Contract: contract, Events: events}
}
