// Code generated by hostcontractgen. DO NOT EDIT.
package registration

import (
	"github.com/dayvidpham/pasture/internal/codegen/ir"
	"github.com/dayvidpham/pasture/internal/lifecycle/model"
	pastureruntime "github.com/dayvidpham/pasture/internal/runtime"
)

func OpenCode2_0_20() Manifest {
	events := []Event{
		{Kind: EventOpenCode2SessionPrompt, NativeName: "session.prompt", AllowedFields: []model.NativeFieldID{}, Identities: []Identity{}, Blocking: Blocking, Mutation: MutationNone, Failure: pastureruntime.FailureThrowFailFast, StopLoop: StopLoopNotApplicable},
		{Kind: EventOpenCode2SessionContext, NativeName: "session.context", AllowedFields: []model.NativeFieldID{}, Identities: []Identity{}, Blocking: Blocking, Mutation: MutationNone, Failure: pastureruntime.FailureThrowFailFast, StopLoop: StopLoopNotApplicable},
		{Kind: EventOpenCode2SessionCompaction, NativeName: "session.compaction", AllowedFields: []model.NativeFieldID{}, Identities: []Identity{}, Blocking: Blocking, Mutation: MutationNone, Failure: pastureruntime.FailureThrowFailFast, StopLoop: StopLoopNotApplicable},
		{Kind: EventOpenCode2SessionGenerate, NativeName: "session.generate", AllowedFields: []model.NativeFieldID{}, Identities: []Identity{}, Blocking: Blocking, Mutation: MutationNone, Failure: pastureruntime.FailureThrowFailFast, StopLoop: StopLoopNotApplicable},
		{Kind: EventOpenCode2SessionTitle, NativeName: "session.title", AllowedFields: []model.NativeFieldID{}, Identities: []Identity{}, Blocking: Blocking, Mutation: MutationNone, Failure: pastureruntime.FailureThrowFailFast, StopLoop: StopLoopNotApplicable},
		{Kind: EventOpenCode2SessionModelRequest, NativeName: "session.model.request", AllowedFields: []model.NativeFieldID{}, Identities: []Identity{}, Blocking: Blocking, Mutation: MutationNone, Failure: pastureruntime.FailureThrowFailFast, StopLoop: StopLoopNotApplicable},
		{Kind: EventOpenCode2SessionHttpRequest, NativeName: "session.http.request", AllowedFields: []model.NativeFieldID{}, Identities: []Identity{}, Blocking: Blocking, Mutation: MutationNone, Failure: pastureruntime.FailureThrowFailFast, StopLoop: StopLoopNotApplicable},
		{Kind: EventOpenCode2SessionHttpResponse, NativeName: "session.http.response", AllowedFields: []model.NativeFieldID{}, Identities: []Identity{}, Blocking: Blocking, Mutation: MutationNone, Failure: pastureruntime.FailureThrowFailFast, StopLoop: StopLoopNotApplicable},
		{Kind: EventOpenCode2SessionExperimentalWsHandshake, NativeName: "session.experimental.ws.handshake", AllowedFields: []model.NativeFieldID{}, Identities: []Identity{}, Blocking: Blocking, Mutation: MutationNone, Failure: pastureruntime.FailureThrowFailFast, StopLoop: StopLoopNotApplicable},
		{Kind: EventOpenCode2SessionExperimentalWsSend, NativeName: "session.experimental.ws.send", AllowedFields: []model.NativeFieldID{}, Identities: []Identity{}, Blocking: Blocking, Mutation: MutationNone, Failure: pastureruntime.FailureThrowFailFast, StopLoop: StopLoopNotApplicable},
		{Kind: EventOpenCode2SessionExperimentalWsReceive, NativeName: "session.experimental.ws.receive", AllowedFields: []model.NativeFieldID{}, Identities: []Identity{}, Blocking: Blocking, Mutation: MutationNone, Failure: pastureruntime.FailureThrowFailFast, StopLoop: StopLoopNotApplicable},
		{Kind: EventOpenCode2SessionRetry, NativeName: "session.retry", AllowedFields: []model.NativeFieldID{}, Identities: []Identity{}, Blocking: Blocking, Mutation: MutationNone, Failure: pastureruntime.FailureThrowFailFast, StopLoop: StopLoopNotApplicable},
		{Kind: EventOpenCode2ToolExecuteBefore, NativeName: "tool.execute.before", AllowedFields: []model.NativeFieldID{FieldOpenCode2SessionID, FieldOpenCode2CallID}, Identities: []Identity{{Field: FieldOpenCode2SessionID, Binding: model.BindingSession, Required: true}, {Field: FieldOpenCode2CallID, Binding: model.BindingToolCall, Required: true}}, Blocking: Blocking, Mutation: MutationNone, Failure: pastureruntime.FailureThrowFailFast, StopLoop: StopLoopNotApplicable},
		{Kind: EventOpenCode2ToolExecuteAfter, NativeName: "tool.execute.after", AllowedFields: []model.NativeFieldID{}, Identities: []Identity{}, Blocking: Blocking, Mutation: MutationNone, Failure: pastureruntime.FailureThrowFailFast, StopLoop: StopLoopNotApplicable},
		{Kind: EventOpenCode2PermissionEvaluate, NativeName: "permission.evaluate", AllowedFields: []model.NativeFieldID{FieldOpenCode2SessionID}, Identities: []Identity{{Field: FieldOpenCode2SessionID, Binding: model.BindingSession, Required: true}}, Blocking: Blocking, Mutation: MutationNone, Failure: pastureruntime.FailureThrowFailFast, StopLoop: StopLoopNotApplicable},
		{Kind: EventOpenCode2ShellCreateBefore, NativeName: "shell.create.before", AllowedFields: []model.NativeFieldID{}, Identities: []Identity{}, Blocking: Blocking, Mutation: MutationNone, Failure: pastureruntime.FailureThrowFailFast, StopLoop: StopLoopNotApplicable},
	}
	contract, err := ir.NewRuntimeContractID(ir.HarnessOpenCode, "2.0.20")
	if err != nil {
		panic(err)
	}
	return Manifest{Harness: ir.HarnessOpenCode, Version: "2.0.20", Contract: contract, Events: events}
}
