package integration_test

import (
	"crypto/sha256"
	"encoding/hex"
	"os"
	"path/filepath"
	"sort"
	"testing"
)

// TestSkills_InstalledTreeIsByteIdenticalToTheShippedBundle proves the skills a
// user receives are exactly the generated bytes Pasture ships — not a rendered,
// rewritten, or re-serialized copy.
//
// The chain proved here is generated output -> embedded bundle -> installed
// tree:
//
//   - OpenCode: the installed tree is compared against the embedded asset tree
//     the binary carries (internal/target/opencode/assets/skills), and that
//     tree is in turn compared against the generated repository output
//     (.opencode/skill), closing the chain.
//   - Codex: the embedded payload is a compressed archive, so the installed
//     tree is compared directly against the generated repository output
//     (.agents/skills).
//
// Only the skills axis is asserted byte-for-byte; agents and hooks are covered
// structurally by the nine-cell isolation test.
func TestSkills_InstalledTreeIsByteIdenticalToTheShippedBundle(t *testing.T) {
	t.Parallel()
	for _, subject := range []struct {
		cell        cellFixture
		installedIn string
		shippedIn   string
		generatedIn string
	}{
		{
			cell:        cellFixture{name: "opencode.skills", harness: "opencode", extension: "skills", marker: ".config/opencode/skills/"},
			installedIn: filepath.Join(".config", "opencode", "skills"),
			shippedIn:   filepath.Join("internal", "target", "opencode", "assets", "skills"),
			generatedIn: filepath.Join(".opencode", "skill"),
		},
		{
			cell:        cellFixture{name: "codex.skills", harness: "codex", extension: "skills", marker: ".agents/skills/"},
			installedIn: filepath.Join(".agents", "skills"),
			generatedIn: filepath.Join(".agents", "skills"),
		},
	} {
		t.Run(subject.cell.name, func(t *testing.T) {
			t.Parallel()
			env := newEnv(t, hostSeed{})
			env.mustRun("install", subject.cell.harness, subject.cell.extension)

			installed := digestTree(t, filepath.Join(env.home, subject.installedIn))
			if len(installed) == 0 {
				t.Fatalf("cell %s installed no skills below %q", subject.cell.name, subject.installedIn)
			}
			generated := digestTree(t, filepath.Join(repoRoot, subject.generatedIn))
			assertSameTree(t, "generated output "+subject.generatedIn, generated, "installed tree", installed)

			if subject.shippedIn != "" {
				shipped := digestTree(t, filepath.Join(repoRoot, subject.shippedIn))
				assertSameTree(t, "embedded bundle "+subject.shippedIn, shipped, "installed tree", installed)
			}

			for path, entry := range installed {
				if entry.mode != 0o644 {
					t.Fatalf("installed skill %q has mode %o, want 0644 so the user can read but not accidentally execute shipped content", path, entry.mode)
				}
			}
		})
	}
}

type treeEntry struct {
	digest string
	mode   os.FileMode
}

// digestTree hashes every regular file below root, keyed by its slash-separated
// path relative to root.
func digestTree(t *testing.T, root string) map[string]treeEntry {
	t.Helper()
	entries := map[string]treeEntry{}
	err := filepath.Walk(root, func(path string, info os.FileInfo, walkErr error) error {
		if walkErr != nil {
			return walkErr
		}
		if info.IsDir() {
			return nil
		}
		if !info.Mode().IsRegular() {
			t.Fatalf("tree %q contains non-regular entry %q (mode %s); shipped skills must be regular files", root, path, info.Mode())
		}
		data, readErr := os.ReadFile(path)
		if readErr != nil {
			return readErr
		}
		rel, relErr := filepath.Rel(root, path)
		if relErr != nil {
			return relErr
		}
		sum := sha256.Sum256(data)
		entries[filepath.ToSlash(rel)] = treeEntry{digest: hex.EncodeToString(sum[:]), mode: info.Mode().Perm()}
		return nil
	})
	if err != nil {
		t.Fatalf("walk %q: %v", root, err)
	}
	return entries
}

func assertSameTree(t *testing.T, wantLabel string, want map[string]treeEntry, gotLabel string, got map[string]treeEntry) {
	t.Helper()
	for _, path := range sortedKeys(want) {
		entry, ok := got[path]
		if !ok {
			t.Fatalf("%s contains %q but %s does not; the delivered skills tree must be byte-identical", wantLabel, path, gotLabel)
		}
		if entry.digest != want[path].digest {
			t.Fatalf("%s and %s disagree on the contents of %q (%s vs %s); the delivered skills tree must be byte-identical",
				wantLabel, gotLabel, path, want[path].digest, entry.digest)
		}
	}
	for _, path := range sortedKeys(got) {
		if _, ok := want[path]; !ok {
			t.Fatalf("%s contains %q but %s does not; the delivered skills tree must be byte-identical", gotLabel, path, wantLabel)
		}
	}
}

func sortedKeys(entries map[string]treeEntry) []string {
	keys := make([]string, 0, len(entries))
	for key := range entries {
		keys = append(keys, key)
	}
	sort.Strings(keys)
	return keys
}
