// Code generated by hostcontractgen. DO NOT EDIT.
package claude

import (
	"github.com/dayvidpham/pasture/internal/lifecycle/model"
	"github.com/dayvidpham/pasture/internal/lifecycle/registration"
)

var fieldNames = map[model.NativeFieldID]string{
	registration.FieldSessionID:           "session_id",
	registration.FieldTranscriptPath:      "transcript_path",
	registration.FieldCWD:                 "cwd",
	registration.FieldPermissionMode:      "permission_mode",
	registration.FieldHookEventName:       "hook_event_name",
	registration.FieldEffort:              "effort",
	registration.FieldAgentID:             "agent_id",
	registration.FieldAgentType:           "agent_type",
	registration.FieldSource:              "source",
	registration.FieldModel:               "model",
	registration.FieldSessionTitle:        "session_title",
	registration.FieldTrigger:             "trigger",
	registration.FieldReason:              "reason",
	registration.FieldPrompt:              "prompt",
	registration.FieldCommandName:         "command_name",
	registration.FieldStopHookActive:      "stop_hook_active",
	registration.FieldError:               "error",
	registration.FieldErrorType:           "error_type",
	registration.FieldToolName:            "tool_name",
	registration.FieldToolInput:           "tool_input",
	registration.FieldToolUseID:           "tool_use_id",
	registration.FieldRequestID:           "request_id",
	registration.FieldToolOutput:          "tool_output",
	registration.FieldBatchResults:        "batch_results",
	registration.FieldFilePath:            "file_path",
	registration.FieldConfigSource:        "config_source",
	registration.FieldMemoryType:          "memory_type",
	registration.FieldLoadReason:          "load_reason",
	registration.FieldGlobs:               "globs",
	registration.FieldTriggerFilePath:     "trigger_file_path",
	registration.FieldParentFilePath:      "parent_file_path",
	registration.FieldAgentTranscriptPath: "agent_transcript_path",
	registration.FieldTeammateName:        "teammate_name",
	registration.FieldTaskID:              "task_id",
	registration.FieldMessage:             "message",
	registration.FieldNotificationType:    "notification_type",
	registration.FieldTitle:               "title",
	registration.FieldContent:             "content",
	registration.FieldFields:              "fields",
	registration.FieldMCPServerName:       "mcp_server_name",
	registration.FieldResponse:            "response",
}
