//go:build ignore

// Command gen writes codebook.gen.go from the pinned runtime lifecycle profiles.
// It is invoked by `go generate ./internal/lifecycle/codebook/...` (wired into
// `make generate`). The output is deterministic, so a second run is zero-diff.
package main

import (
	"fmt"
	"go/format"
	"os"

	"github.com/dayvidpham/pasture/internal/lifecycle/codebook"
)

func main() {
	body, err := codebook.BuildCanonicalBody()
	if err != nil {
		fmt.Fprintf(os.Stderr, "codebook generate: build canonical body: %v\n", err)
		os.Exit(1)
	}
	source := fmt.Sprintf(`// Code generated by "go generate"; DO NOT EDIT.
// Source: the pinned runtime lifecycle profiles (internal/runtime).

package codebook

// canonicalBody is the content-addressed lifecycle interpretation vocabulary
// derived from the pinned runtime lifecycle profiles. Its sha256 is the active
// codebook coordinate's content identity.
var canonicalBody = []byte(%q)
`, body)
	formatted, err := format.Source([]byte(source))
	if err != nil {
		fmt.Fprintf(os.Stderr, "codebook generate: gofmt generated source: %v\n", err)
		os.Exit(1)
	}
	if err := os.WriteFile("codebook.gen.go", formatted, 0o644); err != nil {
		fmt.Fprintf(os.Stderr, "codebook generate: write codebook.gen.go: %v\n", err)
		os.Exit(1)
	}
}
