package main

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
	"path/filepath"

	"github.com/dayvidpham/pasture/internal/lifecycle/ingress/internal/hostcontract"
	"github.com/dayvidpham/pasture/internal/lifecycle/model"
)

func main() {
	root, err := moduleRoot()
	if err != nil {
		fatal(err)
	}
	contract := hostcontract.ClaudeCode2_1_210()
	outputs := map[string][]byte{
		filepath.Join(root, "internal/lifecycle/registration/event_kinds.gen.go"):       renderKinds(contract),
		filepath.Join(root, "internal/lifecycle/registration/claude_2_1_210.gen.go"):    renderManifest(contract),
		filepath.Join(root, "internal/lifecycle/ingress/claude/payload_2_1_210.gen.go"): renderPayload(contract),
	}
	for path, source := range outputs {
		formatted, err := format.Source(source)
		if err != nil {
			fatal(fmt.Errorf("format %s: %w\n%s", path, err, source))
		}
		if err := os.WriteFile(path, formatted, 0o644); err != nil {
			fatal(fmt.Errorf("write %s: %w", path, err))
		}
	}
}

func moduleRoot() (string, error) {
	dir, err := os.Getwd()
	if err != nil {
		return "", err
	}
	for {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			return dir, nil
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			return "", fmt.Errorf("hostcontractgen: go.mod not found above %s", dir)
		}
		dir = parent
	}
}

func renderKinds(c hostcontract.Contract) []byte {
	var b bytes.Buffer
	fmt.Fprint(&b, "// Code generated by hostcontractgen. DO NOT EDIT.\npackage registration\n\nimport \"github.com/dayvidpham/pasture/internal/lifecycle/model\"\n\n")
	fmt.Fprintln(&b, "const (")
	for i, e := range c.Events {
		suffix := ""
		if i == 0 {
			suffix = " model.ContractEventKind = iota + 1"
		}
		fmt.Fprintf(&b, "\t%s%s\n", e.Symbol, suffix)
	}
	fmt.Fprintln(&b, ")\n\nconst (")
	for i, f := range c.Fields {
		suffix := ""
		if i == 0 {
			suffix = " model.NativeFieldID = iota + 1"
		}
		fmt.Fprintf(&b, "\t%s%s\n", f.Symbol, suffix)
	}
	fmt.Fprintln(&b, ")")
	return b.Bytes()
}

func renderManifest(c hostcontract.Contract) []byte {
	var b bytes.Buffer
	fmt.Fprint(&b, "// Code generated by hostcontractgen. DO NOT EDIT.\npackage registration\n\nimport (\n\t\"github.com/dayvidpham/pasture/internal/codegen/ir\"\n\t\"github.com/dayvidpham/pasture/internal/lifecycle/model\"\n)\n\n")
	fmt.Fprintln(&b, "func ClaudeCode2_1_210() Manifest {\n\tevents := []Event{")
	fieldSymbols := map[uint16]string{}
	for _, f := range c.Fields {
		fieldSymbols[uint16(f.ID)] = f.Symbol
	}
	for _, e := range c.Events {
		fmt.Fprintf(&b, "\t\t{Kind:%s, NativeName:%q, AllowedFields:[]model.NativeFieldID{", e.Symbol, e.Name)
		for _, f := range e.Fields {
			fmt.Fprintf(&b, "%s,", fieldSymbols[uint16(f)])
		}
		fmt.Fprint(&b, "}, Identities:[]Identity{")
		for _, id := range e.Identities {
			fmt.Fprintf(&b, "{Field:%s,Binding:%s,Required:%t},", fieldSymbols[uint16(id.Field)], binding(id.Binding), id.Required)
		}
		fmt.Fprintf(&b, "}, Blocking:%s, Mutation:%s, Failure:%s, StopLoop:%s},\n", blocking(e.Blocking), mutation(e.Mutation), failure(e.Failure), stop(e.StopLoop))
	}
	fmt.Fprintf(&b, "\t}\n\tcontract, err := ir.NewRuntimeContractID(ir.HarnessClaudeCode, %q)\n\tif err != nil { panic(err) }\n\treturn Manifest{Harness:ir.HarnessClaudeCode, Version:%q, Contract:contract, Events:events}\n}\n", c.Version, c.Version)
	return b.Bytes()
}

func renderPayload(c hostcontract.Contract) []byte {
	var b bytes.Buffer
	fmt.Fprintln(&b, "// Code generated by hostcontractgen. DO NOT EDIT.\npackage claude\n\nimport (\n\t\"github.com/dayvidpham/pasture/internal/lifecycle/model\"\n\t\"github.com/dayvidpham/pasture/internal/lifecycle/registration\"\n)\n\nvar fieldNames = map[model.NativeFieldID]string{")
	for _, f := range c.Fields {
		fmt.Fprintf(&b, "\tregistration.%s: %q,\n", f.Symbol, f.Name)
	}
	fmt.Fprintln(&b, "}")
	return b.Bytes()
}

func blocking(v hostcontract.BlockingMode) string {
	return []string{"", "NonBlocking", "Blocking", "ConditionallyBlocking"}[int(v)]
}
func mutation(v hostcontract.MutationMode) string {
	return []string{"", "MutationNone", "MutationInput"}[int(v)]
}
func failure(v hostcontract.FailureMode) string {
	return []string{"", "FailureReportAndContinue", "FailureExitTwoBlocks"}[int(v)]
}
func stop(v hostcontract.StopLoopPolicy) string {
	return []string{"", "StopLoopNotApplicable", "StopLoopConsultWhenInactive"}[int(v)]
}
func binding(v model.NativeBindingKind) string {
	return map[model.NativeBindingKind]string{model.BindingSession: "model.BindingSession", model.BindingRequest: "model.BindingRequest", model.BindingToolCall: "model.BindingToolCall", model.BindingAgent: "model.BindingAgent"}[v]
}
func fatal(err error) { fmt.Fprintln(os.Stderr, err); os.Exit(1) }
