package main

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"strings"

	"github.com/dayvidpham/pasture/internal/lifecycle/ingress/internal/hostcontract"
	"github.com/dayvidpham/pasture/internal/lifecycle/model"
	pastureruntime "github.com/dayvidpham/pasture/internal/runtime"
)

func main() {
	root, err := moduleRoot()
	if err != nil {
		fatal(err)
	}
	contract := hostcontract.ClaudeCode2_1_261()
	opencode := hostcontract.OpenCode1_18_29()
	codex := hostcontract.Codex0_153_0()
	// The lifecycle-event inventory rows are emitted in THIS same walk that
	// renders the registration manifests, from the identical pinned contracts,
	// so the inventory table and registration can never drift from each other
	// or from the contracts (D6, by construction). Order follows the walk
	// (Claude, then OpenCode, then Codex); inventory.Table re-sorts.
	lifecycleContracts := []inventoryHarnessContract{
		{harnessExpr: "ir.HarnessClaudeCode", contract: contract},
		{harnessExpr: "ir.HarnessOpenCode", contract: opencode},
		{harnessExpr: "ir.HarnessCodex", contract: codex},
	}
	// Every versioned file and function name is derived from Contract.Version,
	// so a moved host version renames the generated surface by generation and
	// never by hand.
	outputs := map[string][]byte{
		filepath.Join(root, "internal/lifecycle/registration/event_kinds.gen.go"):                            renderKinds(contract, opencode, codex),
		filepath.Join(root, "internal/lifecycle/registration/claude_"+versionToken(contract)+".gen.go"):      renderManifest(contract),
		filepath.Join(root, "internal/lifecycle/ingress/claude/payload_"+versionToken(contract)+".gen.go"):   renderPayload(contract),
		filepath.Join(root, "internal/lifecycle/registration/opencode_"+versionToken(opencode)+".gen.go"):    renderProviderManifest(opencode, "OpenCode"+versionToken(opencode), "ir.HarnessOpenCode"),
		filepath.Join(root, "internal/lifecycle/ingress/opencode/payload_"+versionToken(opencode)+".gen.go"): renderProviderPayload(opencode, "opencode"),
		filepath.Join(root, "internal/lifecycle/registration/codex_"+versionToken(codex)+".gen.go"):          renderProviderManifest(codex, "Codex"+versionToken(codex), "ir.HarnessCodex"),
		filepath.Join(root, "internal/lifecycle/ingress/codex/payload_"+versionToken(codex)+".gen.go"):       renderProviderPayload(codex, "codex"),
		filepath.Join(root, "internal/inventory/lifecycle_events.gen.go"):                                    renderInventoryLifecycleEvents(lifecycleContracts),
	}
	for path, source := range outputs {
		formatted, err := format.Source(source)
		if err != nil {
			fatal(fmt.Errorf("format %s: %w\n%s", path, err, source))
		}
		if err := os.WriteFile(path, formatted, 0o644); err != nil {
			fatal(fmt.Errorf("write %s: %w", path, err))
		}
	}
}

// versionToken spells a host version the way Go identifiers and file names
// carry it: dots become underscores (2.1.261 -> 2_1_261). Every versioned
// output file name and generated function name is built from it, so when the
// recorded host version moves, the generated surface is renamed by generation
// and never by hand; a test pins that the names follow the contract version.
func versionToken(c hostcontract.Contract) string {
	return strings.ReplaceAll(c.Version, ".", "_")
}

func moduleRoot() (string, error) {
	dir, err := os.Getwd()
	if err != nil {
		return "", err
	}
	for {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			return dir, nil
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			return "", fmt.Errorf("hostcontractgen: go.mod not found above %s", dir)
		}
		dir = parent
	}
}

// inventoryHarnessContract pairs a pinned host contract with the ir harness
// selector expression its inventory rows are keyed by.
type inventoryHarnessContract struct {
	harnessExpr string
	contract    hostcontract.Contract
}

// renderInventoryLifecycleEvents emits internal/inventory/lifecycle_events.gen.go:
// one lifecycle-event Row per contract event, keyed by (harness, lifecycle-event,
// native name). It is emitted in the same walk as the registration manifests
// (see main), so every registration event has exactly its row by construction.
// The generated file is `package inventory` and assigns that package's
// lifecycleEventRows slice via init; this generator writes text only and never
// imports internal/inventory.
func renderInventoryLifecycleEvents(entries []inventoryHarnessContract) []byte {
	var b bytes.Buffer
	fmt.Fprint(&b, "// Code generated by hostcontractgen. DO NOT EDIT.\npackage inventory\n\nimport \"github.com/dayvidpham/pasture/internal/codegen/ir\"\n\nfunc init() {\n\tlifecycleEventRows = []Row{\n")
	for _, e := range entries {
		for _, ev := range e.contract.Events {
			fmt.Fprintf(&b, "\t\t{Key{Harness: %s, Kind: KindLifecycleEvent, ID: %q}},\n", e.harnessExpr, ev.Name)
		}
	}
	fmt.Fprint(&b, "\t}\n}\n")
	return b.Bytes()
}

func renderKinds(contracts ...hostcontract.Contract) []byte {
	var b bytes.Buffer
	fmt.Fprint(&b, "// Code generated by hostcontractgen. DO NOT EDIT.\npackage registration\n\nimport \"github.com/dayvidpham/pasture/internal/lifecycle/model\"\n\n")
	fmt.Fprintln(&b, "const (")
	eventIndex := 0
	for _, c := range contracts {
		for _, e := range c.Events {
			suffix := ""
			if eventIndex == 0 {
				suffix = " model.ContractEventKind = iota + 1"
			}
			fmt.Fprintf(&b, "\t%s%s\n", e.Symbol, suffix)
			eventIndex++
		}
	}
	fmt.Fprintln(&b, ")\n\nconst (")
	fieldIndex := 0
	for _, c := range contracts {
		for _, f := range c.Fields {
			suffix := ""
			if fieldIndex == 0 {
				suffix = " model.NativeFieldID = iota + 1"
			}
			fmt.Fprintf(&b, "\t%s%s\n", f.Symbol, suffix)
			fieldIndex++
		}
	}
	fmt.Fprintln(&b, ")")
	return b.Bytes()
}

// renderProviderManifest renders a registration Manifest constructor for any
// non-Claude provider whose contract is source-defined in the hostcontract
// package. It is parameterised by the exported constructor name and the ir
// harness selector expression so every such provider (OpenCode, Codex, and any
// future addition) shares one renderer instead of a per-provider copy. Claude
// keeps its own renderer only because it additionally emits a native field-name
// accessor.
func renderProviderManifest(c hostcontract.Contract, funcName, harnessExpr string) []byte {
	var b bytes.Buffer
	fmt.Fprint(&b, "// Code generated by hostcontractgen. DO NOT EDIT.\npackage registration\n\nimport (\n\t\"github.com/dayvidpham/pasture/internal/codegen/ir\"\n\t\"github.com/dayvidpham/pasture/internal/lifecycle/model\"\n\tpastureruntime \"github.com/dayvidpham/pasture/internal/runtime\"\n)\n\n")
	fmt.Fprintf(&b, "func %s() Manifest {\n\tevents := []Event{\n", funcName)
	fieldSymbols := map[uint16]string{}
	for _, f := range c.Fields {
		fieldSymbols[uint16(f.ID)] = f.Symbol
	}
	for _, e := range c.Events {
		fmt.Fprintf(&b, "\t\t{Kind:%s, NativeName:%q, AllowedFields:[]model.NativeFieldID{", e.Symbol, e.Name)
		for _, f := range e.Fields {
			fmt.Fprintf(&b, "%s,", fieldSymbols[uint16(f)])
		}
		fmt.Fprint(&b, "}, Identities:[]Identity{")
		for _, id := range e.Identities {
			fmt.Fprintf(&b, "{Field:%s,Binding:%s,Required:%t},", fieldSymbols[uint16(id.Field)], binding(id.Binding), id.Required)
		}
		fmt.Fprintf(&b, "}, Blocking:%s, Mutation:%s, Failure:%s, StopLoop:%s},\n", blocking(e.Blocking), mutation(e.Mutation), failureIdent(e.Failure), stop(e.StopLoop))
	}
	fmt.Fprintf(&b, "\t}\n\tcontract, err := ir.NewRuntimeContractID(%s, %q)\n\tif err != nil { panic(err) }\n\treturn Manifest{Harness:%s, Version:%q, Contract:contract, Events:events}\n}\n", harnessExpr, c.Version, harnessExpr, c.Version)
	return b.Bytes()
}

// renderProviderPayload renders the ingress field-name map for any non-Claude
// provider (OpenCode, Codex, and future additions), parameterised by the ingress
// package name.
func renderProviderPayload(c hostcontract.Contract, pkg string) []byte {
	var b bytes.Buffer
	fmt.Fprintf(&b, "// Code generated by hostcontractgen. DO NOT EDIT.\npackage %s\n\nimport (\n\t\"github.com/dayvidpham/pasture/internal/lifecycle/model\"\n\t\"github.com/dayvidpham/pasture/internal/lifecycle/registration\"\n)\n\nvar fieldNames = map[model.NativeFieldID]string{\n", pkg)
	for _, f := range c.Fields {
		fmt.Fprintf(&b, "\tregistration.%s: %q,\n", f.Symbol, f.Name)
	}
	fmt.Fprintln(&b, "}")
	return b.Bytes()
}

func renderManifest(c hostcontract.Contract) []byte {
	var b bytes.Buffer
	fmt.Fprint(&b, "// Code generated by hostcontractgen. DO NOT EDIT.\npackage registration\n\nimport (\n\t\"github.com/dayvidpham/pasture/internal/codegen/ir\"\n\t\"github.com/dayvidpham/pasture/internal/lifecycle/model\"\n\tpastureruntime \"github.com/dayvidpham/pasture/internal/runtime\"\n)\n\n")
	fmt.Fprintf(&b, "func ClaudeCode%s() Manifest {\n\tevents := []Event{\n", versionToken(c))
	fieldSymbols := map[uint16]string{}
	for _, f := range c.Fields {
		fieldSymbols[uint16(f.ID)] = f.Symbol
	}
	for _, e := range c.Events {
		fmt.Fprintf(&b, "\t\t{Kind:%s, NativeName:%q, AllowedFields:[]model.NativeFieldID{", e.Symbol, e.Name)
		for _, f := range e.Fields {
			fmt.Fprintf(&b, "%s,", fieldSymbols[uint16(f)])
		}
		fmt.Fprint(&b, "}, Identities:[]Identity{")
		for _, id := range e.Identities {
			fmt.Fprintf(&b, "{Field:%s,Binding:%s,Required:%t},", fieldSymbols[uint16(id.Field)], binding(id.Binding), id.Required)
		}
		fmt.Fprintf(&b, "}, Blocking:%s, Mutation:%s, Failure:%s, StopLoop:%s},\n", blocking(e.Blocking), mutation(e.Mutation), failureIdent(e.Failure), stop(e.StopLoop))
	}
	fmt.Fprintf(&b, "\t}\n\tcontract, err := ir.NewRuntimeContractID(ir.HarnessClaudeCode, %q)\n\tif err != nil { panic(err) }\n\treturn Manifest{Harness:ir.HarnessClaudeCode, Version:%q, Contract:contract, Events:events}\n}\n", c.Version, c.Version)
	fmt.Fprintf(&b, "\nfunc ClaudeCode%sNativeFieldNames() map[model.NativeFieldID]string {\n\treturn map[model.NativeFieldID]string{\n", versionToken(c))
	for _, f := range c.Fields {
		fmt.Fprintf(&b, "\t\t%s: %q,\n", f.Symbol, f.Name)
	}
	fmt.Fprintln(&b, "\t}\n}")
	return b.Bytes()
}

func renderPayload(c hostcontract.Contract) []byte {
	var b bytes.Buffer
	fmt.Fprintln(&b, "// Code generated by hostcontractgen. DO NOT EDIT.\npackage claude\n\nimport (\n\t\"github.com/dayvidpham/pasture/internal/lifecycle/model\"\n\t\"github.com/dayvidpham/pasture/internal/lifecycle/registration\"\n)\n\nvar fieldNames = map[model.NativeFieldID]string{")
	for _, f := range c.Fields {
		fmt.Fprintf(&b, "\tregistration.%s: %q,\n", f.Symbol, f.Name)
	}
	fmt.Fprintln(&b, "}")
	return b.Bytes()
}

func blocking(v hostcontract.BlockingMode) string {
	return []string{"", "NonBlocking", "Blocking", "ConditionallyBlocking"}[int(v)]
}
func mutation(v hostcontract.MutationMode) string {
	return []string{"", "MutationNone", "MutationInput"}[int(v)]
}

// failureIdent renders one runtime.FailureMode arm as the qualified Go
// identifier the generated manifests refer to. There is exactly ONE FailureMode
// vocabulary in the tree (internal/runtime), so the generated registration data
// keeps the native behavior the pinned contract declared: no arm is folded into
// another on the way out.
//
// The switch is exhaustive over the six declared arms. An unknown value can
// only mean a new arm was added to internal/runtime without teaching this
// renderer, so generation stops here rather than writing a manifest that
// silently mislabels a native failure behavior.
func failureIdent(v pastureruntime.FailureMode) string {
	switch v {
	case pastureruntime.FailureReportAndContinue:
		return "pastureruntime.FailureReportAndContinue"
	case pastureruntime.FailureExitTwoBlocks:
		return "pastureruntime.FailureExitTwoBlocks"
	case pastureruntime.FailureStrictHook:
		return "pastureruntime.FailureStrictHook"
	case pastureruntime.FailureStrictExitTwoBlocks:
		return "pastureruntime.FailureStrictExitTwoBlocks"
	case pastureruntime.FailureThrowFailFast:
		return "pastureruntime.FailureThrowFailFast"
	case pastureruntime.FailureObserveOnly:
		return "pastureruntime.FailureObserveOnly"
	default:
		fatal(fmt.Errorf(
			"hostcontractgen: cannot render failure mode %d as a Go identifier, "+
				"because it is not one of the six arms of runtime.FailureMode; "+
				"this happened in failureIdent while rendering a registration manifest; "+
				"the manifest would otherwise label a native failure behavior wrongly, "+
				"and every generated adapter would inherit that label; "+
				"add the new arm to failureIdent in "+
				"internal/lifecycle/ingress/cmd/hostcontractgen/main.go",
			uint8(v)))
		return ""
	}
}
func stop(v hostcontract.StopLoopPolicy) string {
	return []string{"", "StopLoopNotApplicable", "StopLoopConsultWhenInactive"}[int(v)]
}
func binding(v model.NativeBindingKind) string {
	return map[model.NativeBindingKind]string{model.BindingSession: "model.BindingSession", model.BindingTurn: "model.BindingTurn", model.BindingRequest: "model.BindingRequest", model.BindingToolCall: "model.BindingToolCall", model.BindingAgent: "model.BindingAgent"}[v]
}
func fatal(err error) { fmt.Fprintln(os.Stderr, err); os.Exit(1) }
