package codegen

import (
	"encoding/json"
	"io/fs"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"testing"
)

// This file is the L2 golden/absence suite for the Python-free, exec-only Codex
// lifecycle transport (Phase 8 decision 2, #65). It proves both the renderer
// contract (in memory) and the committed generated artifacts on disk. The
// on-disk assertions are expected to FAIL until L3 regenerates .codex/** and
// deletes the stale Python adapter — that failing state is the TDD specification
// L3 implements against.

// codexLifecycleTransportRoot is the committed generated lifecycle transport
// tree the audit scopes to. It deliberately excludes the agents package: only
// the hooks package carries the lifecycle transport.
const codexLifecycleTransportRoot = ".codex/hooks"

// expectedCodexRunner is the single source of truth for a runner's exact bytes
// in the tests, mirroring the production renderCodexEventRunner so a drift in
// either direction is caught.
func expectedCodexRunner(event string) string {
	return "#!/usr/bin/env sh\n" +
		"# Code generated by Pasture. DO NOT EDIT.\n" +
		"exec \"${PASTURE_BIN:-pasture}\" hook lifecycle" +
		" --harness codex --event " + event + " --host-version 0.146.0\n"
}

// TestCodexRunnerIsExecOnly proves each generated runner is a three-line,
// exec-only shim: shebang, provenance comment, and a single exec of the built
// Pasture CLI. It carries no JSON handling, no branching, and no filesystem
// probing — the shim's only job is binary resolution plus exec, so exact stdin
// passes through by inheritance.
func TestCodexRunnerIsExecOnly(t *testing.T) {
	t.Parallel()
	for _, event := range codexLifecycleEventNamesForTest() {
		event := event
		t.Run(event, func(t *testing.T) {
			t.Parallel()
			runner := renderCodexEventRunner(event)

			if runner != expectedCodexRunner(event) {
				t.Fatalf("runner for %s is not the canonical exec-only shim:\n--- got ---\n%s\n--- want ---\n%s", event, runner, expectedCodexRunner(event))
			}

			lines := strings.Split(strings.TrimRight(runner, "\n"), "\n")
			if len(lines) != 3 {
				t.Fatalf("runner for %s has %d lines, want exactly 3 (shebang, comment, exec); a fourth line is branching/logic the transport must not carry:\n%s", event, len(lines), runner)
			}
			if lines[0] != "#!/usr/bin/env sh" {
				t.Errorf("runner for %s shebang = %q", event, lines[0])
			}
			if !strings.HasPrefix(lines[2], "exec \"${PASTURE_BIN:-pasture}\" hook lifecycle ") {
				t.Errorf("runner for %s does not exec the built CLI: %q", event, lines[2])
			}

			// No JSON handling, no branching, no transcript/dir probing, no
			// Python, no caller-selected operation env.
			for _, forbidden := range []string{
				"python", "python3", "pasture-lifecycle", "SCRIPT_DIR", "dirname",
				"PASTURE_ADAPTER", "if ", "case ", "cat ", "echo ", "printf", "jq", "grep", "read ",
			} {
				if strings.Contains(runner, forbidden) {
					t.Errorf("runner for %s contains forbidden non-exec token %q; the shim must be exec-only:\n%s", event, forbidden, runner)
				}
			}
		})
	}
}

// TestCodexRunnerExactPreToolUseAndSessionStartLines locks the two events that
// carry authentic-capture evidence to their exact production exec lines, so the
// only two events allowed activation proof can never silently change contract.
func TestCodexRunnerExactPreToolUseAndSessionStartLines(t *testing.T) {
	t.Parallel()
	cases := map[string]string{
		"PreToolUse":   "exec \"${PASTURE_BIN:-pasture}\" hook lifecycle --harness codex --event PreToolUse --host-version 0.146.0",
		"SessionStart": "exec \"${PASTURE_BIN:-pasture}\" hook lifecycle --harness codex --event SessionStart --host-version 0.146.0",
	}
	for event, wantExec := range cases {
		runner := renderCodexEventRunner(event)
		if !strings.Contains(runner, wantExec+"\n") {
			t.Errorf("runner for %s missing exact exec line %q:\n%s", event, wantExec, runner)
		}
	}
}

// TestCodexHooksJSONUsesPlainCommandStrings proves every hooks.json entry is a
// plain, variable-free command string (`sh .codex/hooks/events/<Event>.sh`).
// Codex 0.146.0 only authentically proves plain-command-string invocation;
// host-side ${VAR} expansion in command strings is unproven and must not appear.
func TestCodexHooksJSONUsesPlainCommandStrings(t *testing.T) {
	t.Parallel()
	wire, err := renderCodexHooksConfig(codexLifecycleEventNamesForTest())
	if err != nil {
		t.Fatalf("renderCodexHooksConfig: %v", err)
	}
	var config codexHooksConfig
	if err := json.Unmarshal([]byte(wire), &config); err != nil {
		t.Fatalf("decode hooks config: %v", err)
	}
	for _, event := range codexLifecycleEventNamesForTest() {
		groups := config.Hooks[event]
		if len(groups) != 1 || len(groups[0].Hooks) != 1 {
			t.Fatalf("event %s has %+v, want exactly one command hook", event, groups)
		}
		command := groups[0].Hooks[0].Command
		want := "sh .codex/hooks/events/" + event + ".sh"
		if command != want {
			t.Errorf("event %s command = %q, want plain string %q", event, command, want)
		}
		if strings.Contains(command, "${") || strings.Contains(command, "$(") {
			t.Errorf("event %s command %q relies on unproven host-side variable expansion", event, command)
		}
	}
}

// TestCodexCommittedRunnersAreExecOnly proves the runners committed to the
// repository are byte-identical to the canonical exec-only shims. Expected to
// FAIL until L3 regenerates .codex/hooks/events/*.sh from the new renderer.
func TestCodexCommittedRunnersAreExecOnly(t *testing.T) {
	t.Parallel()
	root := testModuleRoot(t)
	for _, event := range codexLifecycleEventNamesForTest() {
		path := filepath.Join(root, ".codex", "hooks", "events", event+".sh")
		got, err := os.ReadFile(path)
		if err != nil {
			t.Errorf("read committed runner %q: %v; run make generate and commit the regenerated transport", path, err)
			continue
		}
		if string(got) != expectedCodexRunner(event) {
			t.Errorf("committed runner %s has drifted from the exec-only shim; run make generate:\n--- committed ---\n%s\n--- want ---\n%s", event, got, expectedCodexRunner(event))
		}
	}
}

// TestCodexCommittedHooksJSONIsPlainAndVariableFree proves the committed
// hooks.json is byte-identical to the plain-command-string renderer output and
// contains no host-side variable expansion in its command strings. Expected to
// FAIL until L3 regenerates .codex/hooks.json.
func TestCodexCommittedHooksJSONIsPlainAndVariableFree(t *testing.T) {
	t.Parallel()
	root := testModuleRoot(t)
	want, err := renderCodexHooksConfig(codexLifecycleEventNamesForTest())
	if err != nil {
		t.Fatalf("renderCodexHooksConfig: %v", err)
	}
	path := filepath.Join(root, ".codex", "hooks.json")
	got, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read committed hooks.json %q: %v; run make generate", path, err)
	}
	if string(got) != want {
		t.Errorf("committed .codex/hooks.json has drifted from the plain-command-string renderer; run make generate:\n--- committed ---\n%s\n--- want ---\n%s", got, want)
	}
	if strings.Contains(string(got), "PLUGIN_ROOT") {
		t.Errorf("committed .codex/hooks.json still relies on ${PLUGIN_ROOT} expansion")
	}
}

// TestCodexLifecycleTransportIsPythonFree walks the committed lifecycle
// transport tree (.codex/hooks and .codex/hooks.json) and proves it carries no
// Python file, no python3 invocation, no reference to the deleted adapter, and
// no caller-selected PASTURE_ADAPTER_* operation env — the hard #65 invariant.
// Expected to FAIL until L3 deletes .codex/hooks/pasture-lifecycle.py and
// regenerates the runners.
func TestCodexLifecycleTransportIsPythonFree(t *testing.T) {
	t.Parallel()
	root := testModuleRoot(t)
	transport := filepath.Join(root, filepath.FromSlash(codexLifecycleTransportRoot))

	forbiddenTokens := []string{
		"python", "python3", "pasture-lifecycle.py",
		"PASTURE_ADAPTER_EVENT", "PASTURE_ADAPTER_OPERATION", "PASTURE_ADAPTER_INPUT",
		"__adapter",
	}

	err := filepath.WalkDir(transport, func(path string, d fs.DirEntry, walkErr error) error {
		if walkErr != nil {
			return walkErr
		}
		if d.IsDir() {
			return nil
		}
		if strings.HasSuffix(path, ".py") {
			t.Errorf("Python file present on the Codex lifecycle transport path: %q; #65 forbids any Python on this path — delete it and regenerate", path)
		}
		if filepath.Base(path) == "pasture-lifecycle.py" {
			t.Errorf("the generated Python lifecycle adapter %q still exists; L3 must delete it", path)
		}
		data, err := os.ReadFile(path)
		if err != nil {
			return err
		}
		lower := strings.ToLower(string(data))
		for _, token := range forbiddenTokens {
			if strings.Contains(lower, strings.ToLower(token)) {
				t.Errorf("Codex lifecycle transport file %q contains forbidden token %q (Python/caller-selected-operation residue)", path, token)
			}
		}
		return nil
	})
	if err != nil {
		t.Fatalf("walk committed Codex lifecycle transport %q: %v", transport, err)
	}

	// The deleted adapter must be gone from disk entirely.
	adapter := filepath.Join(root, ".codex", "hooks", "pasture-lifecycle.py")
	if _, statErr := os.Stat(adapter); statErr == nil {
		t.Errorf("%q still exists; L3 must git rm the generated Python adapter", adapter)
	}

	// hooks.json (the transport entrypoint config) must also be Python-free.
	hooksJSON, err := os.ReadFile(filepath.Join(root, ".codex", "hooks.json"))
	if err != nil {
		t.Fatalf("read committed hooks.json: %v", err)
	}
	for _, token := range forbiddenTokens {
		if strings.Contains(strings.ToLower(string(hooksJSON)), strings.ToLower(token)) {
			t.Errorf("committed .codex/hooks.json contains forbidden token %q", token)
		}
	}
}

// TestCodexCommittedHooksPackageInventoryHasNoPythonAdapter proves the committed
// hooks package holds exactly the exec-only event runners and hooks.json — and
// no Python adapter file. Expected to FAIL until L3 deletes the adapter.
func TestCodexCommittedHooksPackageInventoryHasNoPythonAdapter(t *testing.T) {
	t.Parallel()
	root := testModuleRoot(t)

	var want []string
	want = append(want, ".codex/hooks.json")
	for _, event := range codexLifecycleEventNamesForTest() {
		want = append(want, ".codex/hooks/events/"+event+".sh")
	}
	sort.Strings(want)

	base := filepath.Join(root, ".codex")
	var got []string
	err := filepath.WalkDir(base, func(path string, d fs.DirEntry, walkErr error) error {
		if walkErr != nil {
			return walkErr
		}
		if d.IsDir() {
			return nil
		}
		rel, err := filepath.Rel(root, path)
		if err != nil {
			return err
		}
		slash := filepath.ToSlash(rel)
		// Scope to the lifecycle transport package (hooks), excluding the
		// separate agents package and the codex.toml manifest.
		if slash == ".codex/hooks.json" || strings.HasPrefix(slash, ".codex/hooks/") {
			got = append(got, slash)
		}
		return nil
	})
	if err != nil {
		t.Fatalf("walk committed .codex tree: %v", err)
	}
	sort.Strings(got)
	if strings.Join(got, "\n") != strings.Join(want, "\n") {
		t.Errorf("committed Codex lifecycle transport inventory drifted; run make generate:\n--- got ---\n%s\n--- want ---\n%s", strings.Join(got, "\n"), strings.Join(want, "\n"))
	}
}

// TestCodexTransportRegenerationIsByteStable proves the transport renderers are
// pure: two independent renders are byte-identical, so `make generate` twice
// yields no second-run diff on this path.
func TestCodexTransportRegenerationIsByteStable(t *testing.T) {
	t.Parallel()
	names := codexLifecycleEventNamesForTest()
	firstConfig, err := renderCodexHooksConfig(names)
	if err != nil {
		t.Fatalf("first hooks config: %v", err)
	}
	secondConfig, err := renderCodexHooksConfig(names)
	if err != nil {
		t.Fatalf("second hooks config: %v", err)
	}
	if firstConfig != secondConfig {
		t.Fatal("renderCodexHooksConfig is not byte-stable across renders")
	}
	for _, event := range names {
		if renderCodexEventRunner(event) != renderCodexEventRunner(event) {
			t.Fatalf("renderCodexEventRunner(%s) is not byte-stable across renders", event)
		}
	}
}

// TestClaudeAndOpenCodeOutputsRemainByteIdentical is the cross-slice guard: this
// slice touches only the Codex transport, so the committed Claude and OpenCode
// generated outputs must stay byte-identical to their freshly rendered pipeline
// output. It renders each harness (Write=false) and compares to disk.
func TestClaudeAndOpenCodeOutputsRemainByteIdentical(t *testing.T) {
	root := testModuleRoot(t)

	claudeFiles, _ := collectHarnessOutputs(t, root, ClaudeCodeTarget)
	assertGeneratedFilesCommitted(t, root, claudeFiles)

	openCodeFiles, _ := collectHarnessOutputs(t, root, OpenCodeTarget)
	assertGeneratedFilesCommitted(t, root, openCodeFiles)
}
