// Package codegen - Codex plugin manifest and lifecycle hook package.
//
// codexManifestEmitter emits the Codex plugin manifest at `.codex/codex.toml`
// plus the pinned host hook configuration and per-event adapters under
// `.codex/hooks/`.
//
// The manifest declares the three independently selectable Codex packages
// (skills, agents, hooks), each by its stable component identity and package
// root, plus the pinned RuntimeContractID the packages were generated against.
// The hooks package remains default-off at the Pasture component-selection
// boundary. When selected, Codex loads the generated per-event command runners;
// none of these files installs a Git hook or changes core.hooksPath.
package codegen

import (
	"encoding/json"
	"fmt"
	"path/filepath"
	"sort"
	"strings"

	"github.com/dayvidpham/pasture/internal/runtime"
)

// codexManifestSchema tags the Codex plugin manifest so a consumer can reject
// an incompatible manifest shape.
const codexManifestSchema = "pasture.codex.manifest.v1"

// codexManifestEmitter implements ManifestEmitter for the Codex target.
type codexManifestEmitter struct{}

// Emit writes the Codex package manifest, host hook configuration, shared
// adapter, and one fixed-event executable per pinned lifecycle event.
func (codexManifestEmitter) Emit(root string, opts GenerateOptions) ([]GeneratedFile, error) {
	metadata, err := lifecycleMetadata(runtime.Codex0_146_0Lifecycle(), "0.146.0", codexNativeFields)
	if err != nil {
		return nil, fmt.Errorf("codegen.codexManifestEmitter.Emit: lifecycle metadata: %w", err)
	}
	adapter, err := renderPythonLifecycleAdapter(metadata)
	if err != nil {
		return nil, fmt.Errorf("codegen.codexManifestEmitter.Emit: lifecycle adapter: %w", err)
	}

	config, err := renderCodexHooksConfig(metadata.Events)
	if err != nil {
		return nil, fmt.Errorf("codegen.codexManifestEmitter.Emit: hooks config: %w", err)
	}
	outputs := []struct {
		path    string
		content string
	}{
		{path: filepath.Join(root, ".codex", "codex.toml"), content: renderCodexManifest()},
		{path: filepath.Join(root, ".codex", "hooks.json"), content: config},
		{path: filepath.Join(root, ".codex", "hooks", "pasture-lifecycle.py"), content: adapter},
	}
	for _, event := range metadata.Events {
		outputs = append(outputs, struct {
			path    string
			content string
		}{
			path:    filepath.Join(root, ".codex", "hooks", "events", event.Name+".sh"),
			content: renderCodexEventExecutable(event.Name),
		})
	}
	sort.Slice(outputs, func(i, j int) bool { return outputs[i].path < outputs[j].path })

	files := make([]GeneratedFile, 0, len(outputs))
	for _, output := range outputs {
		generated, err := writeFullGeneratedFile(output.path, output.content, opts)
		if err != nil {
			return nil, fmt.Errorf(
				"codegen.codexManifestEmitter.Emit: write %q failed - check that output root %q is writable: %w",
				output.path, root, err,
			)
		}
		files = append(files, generated)
	}
	return files, nil
}

type codexHookCommand struct {
	Type          string `json:"type"`
	Command       string `json:"command"`
	Timeout       int    `json:"timeout"`
	StatusMessage string `json:"statusMessage"`
}

type codexHookGroup struct {
	Matcher *string            `json:"matcher,omitempty"`
	Hooks   []codexHookCommand `json:"hooks"`
}

type codexHooksConfig struct {
	Hooks map[string][]codexHookGroup `json:"hooks"`
}

func renderCodexHooksConfig(events []lifecycleEventMetadata) (string, error) {
	config := codexHooksConfig{Hooks: make(map[string][]codexHookGroup, len(events))}
	for _, event := range events {
		var matcher *string
		switch event.Name {
		case "SessionStart", "PreToolUse", "PermissionRequest", "PostToolUse", "PreCompact", "PostCompact", "SubagentStart", "SubagentStop":
			value := ""
			matcher = &value
		}
		config.Hooks[event.Name] = []codexHookGroup{{
			Matcher: matcher,
			Hooks: []codexHookCommand{{
				Type:          "command",
				Command:       "sh ${PLUGIN_ROOT}/hooks/events/" + event.Name + ".sh",
				Timeout:       600,
				StatusMessage: "Consulting Pasture lifecycle state",
			}},
		}}
	}
	wire, err := json.MarshalIndent(config, "", "  ")
	if err != nil {
		return "", err
	}
	return string(wire) + "\n", nil
}

func renderCodexEventExecutable(event string) string {
	return "#!/usr/bin/env sh\n" +
		"# Code generated by Pasture. DO NOT EDIT.\n" +
		"set -eu\n" +
		"SCRIPT_DIR=$(CDPATH= cd -- \"$(dirname -- \"$0\")\" && pwd)\n" +
		"exec python3 \"${SCRIPT_DIR}/../pasture-lifecycle.py\" --event " + tomlString(event) + "\n"
}

// renderCodexManifest builds the deterministic `.codex/codex.toml` content. The
// package roots are written in slash form so the manifest is portable across
// host path separators.
func renderCodexManifest() string {
	var b strings.Builder
	b.WriteString("# Code-generated by Pasture; DO NOT EDIT.\n")
	b.WriteString("# Codex plugin manifest: three independently selectable packages.\n")
	fmt.Fprintf(&b, "schema = %s\n", tomlString(codexManifestSchema))
	fmt.Fprintf(&b, "name = %s\n", tomlString("pasture-codex"))
	fmt.Fprintf(&b, "runtime_contract = %s\n", tomlString(CodexRuntimeContractID().String()))
	b.WriteString("\n")

	b.WriteString("[packages.skills]\n")
	fmt.Fprintf(&b, "id = %s\n", tomlString(codexSkillsComponent.String()))
	fmt.Fprintf(&b, "path = %s\n", tomlString(codexSkillRoot))
	b.WriteString("enabled = true\n")
	b.WriteString("\n")

	b.WriteString("[packages.agents]\n")
	fmt.Fprintf(&b, "id = %s\n", tomlString(codexAgentsComponent.String()))
	fmt.Fprintf(&b, "path = %s\n", tomlString(codexAgentsRoot))
	b.WriteString("enabled = true\n")
	b.WriteString("\n")

	b.WriteString("[packages.hooks]\n")
	fmt.Fprintf(&b, "id = %s\n", tomlString(codexHooksComponent.String()))
	fmt.Fprintf(&b, "path = %s\n", tomlString(codexHooksRoot))
	b.WriteString("enabled = false\n")
	return b.String()
}

// codexHostVersionLabel returns the pinned Codex host version spelling used in
// generated prose, derived from the pinned RuntimeContractID so the label can
// never drift from the contract the target lowers against.
func codexHostVersionLabel() string {
	id := CodexRuntimeContractID().String()
	if at := strings.LastIndexByte(id, '@'); at >= 0 {
		return id[at+1:]
	}
	return id
}
