// Package codegen — Codex plugin manifest and default-off hooks package.
//
// codexManifestEmitter emits the Codex plugin manifest at `.codex/codex.toml`
// and the default-off hooks package marker at `.codex/hooks/README.md`.
//
// The manifest declares the three independently selectable Codex packages
// (skills, agents, hooks), each by its stable component identity and package
// root, plus the pinned RuntimeContractID the packages were generated against.
// The hooks package is marked `enabled = false`: Codex 0.144.1 exposes no hook
// runtime, so the package ships a single explanatory marker and is inert by
// default. This keeps the hooks package a real, selectable-in-isolation package
// (its own root, its own component identity) while emitting no active behavior —
// matching the "default-off hooks" requirement and the "no Git/Beads hooks"
// non-scope.
package codegen

import (
	"fmt"
	"path/filepath"
	"strings"
)

// codexManifestSchema tags the Codex plugin manifest so a consumer can reject
// an incompatible manifest shape.
const codexManifestSchema = "pasture.codex.manifest.v1"

// codexManifestEmitter implements ManifestEmitter for the Codex target.
type codexManifestEmitter struct{}

// Emit writes the Codex plugin manifest and the default-off hooks marker,
// returning both files in deterministic path order.
func (codexManifestEmitter) Emit(root string, opts GenerateOptions) ([]GeneratedFile, error) {
	manifestPath := filepath.Join(root, ".codex", "codex.toml")
	manifest, err := writeFullGeneratedFile(manifestPath, renderCodexManifest(), opts)
	if err != nil {
		return nil, fmt.Errorf(
			"codegen.codexManifestEmitter.Emit: write %q failed — "+
				"check that the output root %q exists and is writable: %w",
			manifestPath, root, err,
		)
	}

	hooksPath := filepath.Join(root, ".codex", "hooks", "README.md")
	hooks, err := writeFullGeneratedFile(hooksPath, renderCodexHooksMarker(), opts)
	if err != nil {
		return nil, fmt.Errorf(
			"codegen.codexManifestEmitter.Emit: write %q failed — "+
				"check that the output root %q exists and is writable: %w",
			hooksPath, root, err,
		)
	}

	return []GeneratedFile{manifest, hooks}, nil
}

// renderCodexManifest builds the deterministic `.codex/codex.toml` content. The
// package roots are written in slash form so the manifest is portable across
// host path separators.
func renderCodexManifest() string {
	var b strings.Builder
	b.WriteString("# Code-generated by Pasture; DO NOT EDIT.\n")
	b.WriteString("# Codex plugin manifest: three independently selectable packages.\n")
	fmt.Fprintf(&b, "schema = %s\n", tomlString(codexManifestSchema))
	fmt.Fprintf(&b, "name = %s\n", tomlString("pasture-codex"))
	fmt.Fprintf(&b, "runtime_contract = %s\n", tomlString(CodexRuntimeContractID().String()))
	b.WriteString("\n")

	b.WriteString("[packages.skills]\n")
	fmt.Fprintf(&b, "id = %s\n", tomlString(codexSkillsComponent.String()))
	fmt.Fprintf(&b, "path = %s\n", tomlString(codexSkillRoot))
	b.WriteString("enabled = true\n")
	b.WriteString("\n")

	b.WriteString("[packages.agents]\n")
	fmt.Fprintf(&b, "id = %s\n", tomlString(codexAgentsComponent.String()))
	fmt.Fprintf(&b, "path = %s\n", tomlString(codexAgentsRoot))
	b.WriteString("enabled = true\n")
	b.WriteString("\n")

	b.WriteString("[packages.hooks]\n")
	fmt.Fprintf(&b, "id = %s\n", tomlString(codexHooksComponent.String()))
	fmt.Fprintf(&b, "path = %s\n", tomlString(codexHooksRoot))
	b.WriteString("enabled = false\n")
	return b.String()
}

// renderCodexHooksMarker builds the single explanatory file the default-off
// hooks package ships. It documents that Codex 0.144.1 exposes no hook runtime,
// so the package is intentionally inert.
func renderCodexHooksMarker() string {
	var b strings.Builder
	b.WriteString("<!-- Code-generated by Pasture; DO NOT EDIT. -->\n")
	b.WriteString("# Pasture Codex hooks package (default-off)\n\n")
	fmt.Fprintf(&b,
		"Codex %s exposes no harness hook runtime, so this package is intentionally\n"+
			"inert: it ships no active hooks and is marked `enabled = false` in\n"+
			"`.codex/codex.toml`.\n\n",
		codexHostVersionLabel(),
	)
	b.WriteString("It exists as a real, independently selectable package so a consumer can\n")
	b.WriteString("select skills and agents without pulling any hook behavior, and so a future\n")
	b.WriteString("Codex hook surface has a stable package identity to grow into. This package\n")
	b.WriteString("never installs Git hooks, Beads hooks, or `core.hooksPath`.\n")
	return b.String()
}

// codexHostVersionLabel returns the pinned Codex host version spelling used in
// generated prose, derived from the pinned RuntimeContractID so the label can
// never drift from the contract the target lowers against.
func codexHostVersionLabel() string {
	id := CodexRuntimeContractID().String()
	if at := strings.LastIndexByte(id, '@'); at >= 0 {
		return id[at+1:]
	}
	return id
}
