package codegen

import (
	"bytes"
	"fmt"
	"go/format"
	"path/filepath"
	"sort"

	"github.com/dayvidpham/pasture/internal/codegen/ir"
)

// emitInventoryRows writes the two authoring-side inventory projections owned by
// the codegen generation root:
//
//   - internal/inventory/commands.gen.go — the command-skill authoring surface
//     (commandSkillDirs) fanned out per enabled harness (UAT resolution 4:
//     uniform (harness, kind, id) key);
//   - internal/inventory/native_functions.gen.go — the native call names the
//     pinned runtime contracts classify native, per harness (codex via
//     codexNativeFunctions, opencode via deriveOpenCodeNativeToolNames; Claude
//     derives none).
//
// The lifecycle-event projection is emitted separately by hostcontractgen in
// the same walk that renders the registration manifests.
//
// Both files are `package inventory` and populate that package's generated-row
// slices via init assignment. This generator emits them as TEXT and never
// imports internal/inventory, preserving the authoring-side-only invariant: no
// production package depends on the table — only generators emit rows into it
// and tests validate it.
func emitInventoryRows(root string, opts GenerateOptions) error {
	commandsSrc, err := renderInventoryCommandRows()
	if err != nil {
		return fmt.Errorf("render commands.gen.go: %w", err)
	}
	commandsFormatted, err := formatGeneratedGo(commandsSrc)
	if err != nil {
		return fmt.Errorf("format commands.gen.go: %w", err)
	}
	if _, err := writeFullGeneratedFile(filepath.Join(root, "internal/inventory/commands.gen.go"), commandsFormatted, opts); err != nil {
		return err
	}

	nativeSrc, err := renderInventoryNativeFunctionRows()
	if err != nil {
		return fmt.Errorf("render native_functions.gen.go: %w", err)
	}
	nativeFormatted, err := formatGeneratedGo(nativeSrc)
	if err != nil {
		return fmt.Errorf("format native_functions.gen.go: %w", err)
	}
	if _, err := writeFullGeneratedFile(filepath.Join(root, "internal/inventory/native_functions.gen.go"), nativeFormatted, opts); err != nil {
		return err
	}
	return nil
}

// renderInventoryCommandRows emits commands.gen.go: every authored command
// (commandSkillDirs key) fanned out across every enabled harness, sorted by
// (harness order, command id) for byte-stable output.
func renderInventoryCommandRows() ([]byte, error) {
	commandIDs := make([]string, 0, len(commandSkillDirs))
	for id := range commandSkillDirs {
		commandIDs = append(commandIDs, id)
	}
	sort.Strings(commandIDs)

	var b bytes.Buffer
	fmt.Fprint(&b, "// Code generated by codegen. DO NOT EDIT.\npackage inventory\n\nimport \"github.com/dayvidpham/pasture/internal/codegen/ir\"\n\nfunc init() {\n\tcommandRows = []Row{\n")
	for _, harness := range ir.EnabledHarnessIDs() {
		expr, err := inventoryHarnessExpr(harness)
		if err != nil {
			return nil, err
		}
		for _, id := range commandIDs {
			fmt.Fprintf(&b, "\t\t{Key{Harness: %s, Kind: KindCommand, ID: %q}},\n", expr, id)
		}
	}
	fmt.Fprint(&b, "\t}\n}\n")
	return b.Bytes(), nil
}

// renderInventoryNativeFunctionRows emits native_functions.gen.go: the native
// call names each harness's pinned contract classifies native, keyed by
// (harness, native-function, call name). Harnesses that derive no native calls
// (Claude) contribute no rows. Every name is DERIVED from the pinned contract,
// never a literal, so the committed rows can never fabricate a native call the
// contract does not classify — the agreement test re-derives and rejects any
// contradiction.
func renderInventoryNativeFunctionRows() ([]byte, error) {
	openCodeNative, err := deriveOpenCodeNativeToolNames()
	if err != nil {
		return nil, fmt.Errorf("derive opencode native tool names: %w", err)
	}
	perHarness := map[ir.HarnessID][]string{
		ir.HarnessCodex:    codexNativeFunctions(),
		ir.HarnessOpenCode: openCodeNative,
	}

	var b bytes.Buffer
	fmt.Fprint(&b, "// Code generated by codegen. DO NOT EDIT.\npackage inventory\n\nimport \"github.com/dayvidpham/pasture/internal/codegen/ir\"\n\nfunc init() {\n\tnativeFunctionRows = []Row{\n")
	for _, harness := range ir.EnabledHarnessIDs() {
		names := perHarness[harness]
		if len(names) == 0 {
			continue
		}
		expr, err := inventoryHarnessExpr(harness)
		if err != nil {
			return nil, err
		}
		sorted := append([]string(nil), names...)
		sort.Strings(sorted)
		for _, name := range sorted {
			fmt.Fprintf(&b, "\t\t{Key{Harness: %s, Kind: KindNativeFunction, ID: %q}},\n", expr, name)
		}
	}
	fmt.Fprint(&b, "\t}\n}\n")
	return b.Bytes(), nil
}

// inventoryHarnessExpr maps an enabled harness id to the ir selector expression
// the generated inventory rows reference. The set is closed
// (ir.EnabledHarnessIDs); an unknown value is a generator bug, not user input.
func inventoryHarnessExpr(harness ir.HarnessID) (string, error) {
	switch harness {
	case ir.HarnessClaudeCode:
		return "ir.HarnessClaudeCode", nil
	case ir.HarnessOpenCode:
		return "ir.HarnessOpenCode", nil
	case ir.HarnessCodex:
		return "ir.HarnessCodex", nil
	default:
		return "", fmt.Errorf(
			"codegen.inventoryHarnessExpr: no inventory selector for harness %q — "+
				"ir.EnabledHarnessIDs gained a harness the inventory generator does not know how to key; "+
				"add its ir.Harness* selector here",
			harness)
	}
}

// formatGeneratedGo gofmt-canonicalises generated Go source so committed
// inventory files are byte-stable and pass the fmt gate.
func formatGeneratedGo(src []byte) (string, error) {
	formatted, err := format.Source(src)
	if err != nil {
		return "", fmt.Errorf("gofmt generated source: %w\n%s", err, src)
	}
	return string(formatted), nil
}
