package codegen

import (
	"encoding/json"
	"fmt"
	"sort"
	"strings"

	"github.com/dayvidpham/pasture/internal/codegen/ir"
	"github.com/dayvidpham/pasture/internal/handlers"
	"github.com/dayvidpham/pasture/internal/runtime"
)

// OpenCodeHooksModulePath is the canonical generated path of the OpenCode
// lifecycle plugin. OpenCode loads project plugins from .opencode/plugins in
// deterministic configuration order.
const OpenCodeHooksModulePath = ".opencode/plugins/pasture-lifecycle.ts"

// deriveOpenCodeNativeToolNames returns, sorted and de-duplicated, exactly the
// native tool names the pinned OpenCode 1.17.18 runtime contract declares — and
// nothing else. It resolves every core orchestration operation against the
// contract via the delivered runtime lookup and collects only the operations the
// contract classifies as native. Semantic-instruction, parent-mediated, and
// unsupported operations contribute no tool name, so a generated artifact can
// never reference an invented OpenCode tool: the allow-list is the contract's
// own declared surface, computed here rather than hand-copied.
func deriveOpenCodeNativeToolNames() ([]string, error) {
	contract := runtime.OpenCode1_17_18()
	seen := make(map[string]struct{})
	var names []string
	for _, kind := range ir.AllOperationKinds() {
		descriptor, ok := runtime.CoreOperationDescriptorFor(kind)
		if !ok {
			// A core operation kind with no shared descriptor would mean the
			// delivered runtime descriptor table drifted from the operation
			// vocabulary; fail closed rather than silently narrow the allow-list.
			return nil, fmt.Errorf(
				"codegen.deriveOpenCodeNativeToolNames: core operation %q has no shared descriptor in the delivered runtime table — "+
					"the runtime descriptor set drifted from ir.AllOperationKinds; regenerate against a runtime revision whose CoreOperationDescriptorFor covers every core kind",
				kind)
		}
		binding, err := runtime.LookupOperationBinding(contract, descriptor)
		if err != nil {
			// Unsupported operations (for OpenCode 1.17.18, stopping an
			// assignment) return a lookup error by contract; they are correctly
			// absent from a native allow-list, so skip rather than fail.
			continue
		}
		call, isNative := binding.Native()
		if !isNative {
			continue
		}
		name := call.CallName()
		if _, dup := seen[name]; dup {
			continue
		}
		seen[name] = struct{}{}
		names = append(names, name)
	}
	sort.Strings(names)
	return names, nil
}

// GenerateOpenCodeHooksModule returns the deterministic self-contained Bun
// plugin for the pinned OpenCode lifecycle contract. Named handlers await the
// hidden production adapter and throw on failure; catch-all events remain
// observe-only and never mutate the output object or manufacture a decision.
func GenerateOpenCodeHooksModule() (string, error) {
	toolNames, err := deriveOpenCodeNativeToolNames()
	if err != nil {
		return "", fmt.Errorf("codegen.GenerateOpenCodeHooksModule: derive native tool allow-list: %w", err)
	}
	metadata, err := lifecycleMetadata(
		runtime.OpenCode1_17_18Lifecycle(),
		"1.17.18",
		func(string) []string { return nil },
	)
	if err != nil {
		return "", fmt.Errorf("codegen.GenerateOpenCodeHooksModule: lifecycle metadata: %w", err)
	}
	metadataJSON, err := json.Marshal(metadata)
	if err != nil {
		return "", fmt.Errorf("codegen.GenerateOpenCodeHooksModule: marshal lifecycle metadata: %w", err)
	}

	quoted := make([]string, len(toolNames))
	for i, n := range toolNames {
		quoted[i] = fmt.Sprintf("%q", n)
	}
	allowList := strings.Join(quoted, ", ")

	var namedHandlers strings.Builder
	for _, event := range metadata.Events {
		if event.Surface != runtime.SurfaceOpenCodeNamedOutput.String() {
			continue
		}
		fmt.Fprintf(&namedHandlers,
			"    async %q(input, output) {\n      await invokeNamed(%q, input, output);\n    },\n",
			event.Name, event.Name,
		)
	}

	const module = `// Code generated by Pasture for OpenCode. DO NOT EDIT.
// Runtime contract: %s
// This plugin is self-contained and requires only Bun plus the built pasture binary.

export const PASTURE_NATIVE_TOOLS = Object.freeze([%s]);
export const PASTURE_RUNTIME_CONTRACT = %q;
const METADATA = %s;
const EVENTS = new Map(METADATA.events.map((event) => [event.name, event]));

function sourceValue(source, name) {
  if (source && Object.prototype.hasOwnProperty.call(source, name)) return source[name];
  if (source?.properties && Object.prototype.hasOwnProperty.call(source.properties, name)) return source.properties[name];
  if (source?.payload?.properties && Object.prototype.hasOwnProperty.call(source.payload.properties, name)) return source.payload.properties[name];
  return undefined;
}

function invocationIdentity(mapping, source) {
  const identities = [];
  for (const identity of mapping.identities) {
    const value = sourceValue(source, identity.name);
    if (value === undefined) {
      if (identity.required) throw new Error("event " + mapping.name + " is missing required native identity " + identity.name);
      continue;
    }
    if (typeof value !== "string" || value.length === 0) throw new Error("native identity " + identity.name + " must be a non-empty string");
    identities.push([identity.name, value]);
  }
  const canonical = JSON.stringify({ event: mapping.name, identities });
  const encoded = Buffer.from(canonical, "utf8").toString("base64url");
  const result = METADATA.harness + "." + encoded;
  if (Buffer.byteLength(result, "utf8") > 4096) throw new Error("correlated native invocation exceeds the hidden adapter identity limit");
  return result;
}

async function invokePasture(mapping, source) {
  const boundEvent = process.env.%s ?? "";
  const operation = process.env.%s ?? "";
  const rawInput = process.env.%s ?? "";
  if (!boundEvent && !operation && !rawInput) return;
  if (!boundEvent || !operation || !rawInput) throw new Error("%s, %s, and %s must either all be set or all be absent");
  if (boundEvent !== mapping.name) return;
  const allowed = METADATA.operations[mapping.semantic] ?? [];
  if (!allowed.includes(operation)) throw new Error("operation " + operation + " is not allowed for " + mapping.semantic + " event " + mapping.name);

  const header = JSON.stringify({
    schema: %q,
    harness: METADATA.harness,
    harnessVersion: METADATA.version,
    harnessContract: METADATA.contract,
    nativeInvocation: invocationIdentity(mapping, source),
    operation,
  });
  // Preserve operation input bytes until handlers.AdapterInvocationEnvelope
  // performs the sole strict semantic decode in the production binary.
  const envelope = header.slice(0, -1) + ',"input":' + rawInput + '}\n';
  if (Buffer.byteLength(envelope, "utf8") > 1048576) throw new Error("generated adapter envelope exceeds 1 MiB; remove native or transcript data from semantic input");

  const binary = process.env.%s ?? "pasture";
  const child = Bun.spawn({
    cmd: [binary, "__adapter", "invoke"],
    stdin: new Blob([envelope]),
    stdout: "pipe",
    stderr: "pipe",
  });
  const [stdout, stderr, exitCode] = await Promise.all([
    new Response(child.stdout).text(),
    new Response(child.stderr).text(),
    child.exited,
  ]);
  if (exitCode !== 0) throw new Error("pasture __adapter invoke exited " + exitCode + ": " + (stderr.trim() || "no diagnostic was returned"));
  let result;
  try {
    result = JSON.parse(stdout);
  } catch (error) {
    throw new Error("pasture adapter result is not JSON: " + error);
  }
  const keys = Object.keys(result).sort();
  if (JSON.stringify(keys) !== JSON.stringify(["operation", "result", "schema"])) throw new Error("pasture adapter result must contain exactly schema, operation, and result");
  if (result.schema !== %q || result.operation !== operation) throw new Error("pasture adapter result schema or operation does not match the invocation");
}

async function invokeNamed(name, input, output) {
  const mapping = EVENTS.get(name);
  if (!mapping || mapping.surface !== "opencode-named-output") throw new Error("named OpenCode lifecycle mapping " + name + " is not pinned");
  // Await without replacing output: mutations made by an earlier plugin remain
  // visible to later plugins and to the native operation.
  await invokePasture(mapping, input);
  void output;
}

export const PastureLifecycle = async ({ client }) => ({
  async event({ event }) {
    const name = event?.type;
    const mapping = EVENTS.get(name);
    if (!mapping || mapping.surface !== "opencode-catch-all-sse") return;
    try {
      await invokePasture(mapping, event);
    } catch (error) {
      // Observation is never a gate and cannot terminate the native event bus.
      console.error("Pasture lifecycle observation failed for " + name + ": " + error);
      void client;
    }
  },
%s  });

export default PastureLifecycle;
`

	return fmt.Sprintf(
		module,
		metadata.Contract,
		allowList,
		metadata.Contract,
		string(metadataJSON),
		adapterEventEnv,
		adapterOperationEnv,
		adapterInputEnv,
		adapterEventEnv,
		adapterOperationEnv,
		adapterInputEnv,
		handlers.AdapterInvocationSchema,
		adapterBinaryEnv,
		handlers.AdapterResultSchema,
		namedHandlers.String(),
	), nil
}

// openCodeHostVersion is the pinned OpenCode host version this target generates
// for. It is display metadata for the generated header; the authoritative
// version bound lives in the runtime contract.
const openCodeHostVersion = "1.17.18"
