// Code generated by "go generate"; DO NOT EDIT.
// Source: the proof declaration tables in opencode_targets.go.

package activation

// OpenCode capture proofs, ordinals 200-299.
const (
	CaptureProofOpenCodeSessionCreated                  CaptureProof = 200
	CaptureProofOpenCodeToolExecuteBefore               CaptureProof = 201
	CaptureProofOpenCode2SessionPrompt                  CaptureProof = 202
	CaptureProofOpenCode2SessionContext                 CaptureProof = 203
	CaptureProofOpenCode2SessionTitle                   CaptureProof = 204
	CaptureProofOpenCode2SessionModelRequest            CaptureProof = 205
	CaptureProofOpenCode2SessionHttpRequest             CaptureProof = 206
	CaptureProofOpenCode2SessionHttpResponse            CaptureProof = 207
	CaptureProofOpenCode2ToolExecuteBefore              CaptureProof = 208
	CaptureProofOpenCode2ToolExecuteAfter               CaptureProof = 209
	CaptureProofOpenCode2PermissionEvaluate             CaptureProof = 210
	CaptureProofOpenCode2SessionCreated                 CaptureProof = 211
	CaptureProofOpenCode2SessionCompaction              CaptureProof = 212
	CaptureProofOpenCode2SessionGenerate                CaptureProof = 213
	CaptureProofOpenCode2SessionExperimentalWsHandshake CaptureProof = 214
	CaptureProofOpenCode2SessionExperimentalWsSend      CaptureProof = 215
	CaptureProofOpenCode2SessionExperimentalWsReceive   CaptureProof = 216
	CaptureProofOpenCode2SessionRetry                   CaptureProof = 217
)

// openCodeGeneratedCaptureProofs lists the generated capture proof arms of opencode_targets.go by name, in ordinal order.
var openCodeGeneratedCaptureProofs = []namedCaptureProof{
	{name: "OpenCodeSessionCreated", proof: CaptureProofOpenCodeSessionCreated},
	{name: "OpenCodeToolExecuteBefore", proof: CaptureProofOpenCodeToolExecuteBefore},
	{name: "OpenCode2SessionPrompt", proof: CaptureProofOpenCode2SessionPrompt},
	{name: "OpenCode2SessionContext", proof: CaptureProofOpenCode2SessionContext},
	{name: "OpenCode2SessionTitle", proof: CaptureProofOpenCode2SessionTitle},
	{name: "OpenCode2SessionModelRequest", proof: CaptureProofOpenCode2SessionModelRequest},
	{name: "OpenCode2SessionHttpRequest", proof: CaptureProofOpenCode2SessionHttpRequest},
	{name: "OpenCode2SessionHttpResponse", proof: CaptureProofOpenCode2SessionHttpResponse},
	{name: "OpenCode2ToolExecuteBefore", proof: CaptureProofOpenCode2ToolExecuteBefore},
	{name: "OpenCode2ToolExecuteAfter", proof: CaptureProofOpenCode2ToolExecuteAfter},
	{name: "OpenCode2PermissionEvaluate", proof: CaptureProofOpenCode2PermissionEvaluate},
	{name: "OpenCode2SessionCreated", proof: CaptureProofOpenCode2SessionCreated},
	{name: "OpenCode2SessionCompaction", proof: CaptureProofOpenCode2SessionCompaction},
	{name: "OpenCode2SessionGenerate", proof: CaptureProofOpenCode2SessionGenerate},
	{name: "OpenCode2SessionExperimentalWsHandshake", proof: CaptureProofOpenCode2SessionExperimentalWsHandshake},
	{name: "OpenCode2SessionExperimentalWsSend", proof: CaptureProofOpenCode2SessionExperimentalWsSend},
	{name: "OpenCode2SessionExperimentalWsReceive", proof: CaptureProofOpenCode2SessionExperimentalWsReceive},
	{name: "OpenCode2SessionRetry", proof: CaptureProofOpenCode2SessionRetry},
}

// OpenCode production proofs, ordinals 200-299.
const (
	ProductionProofOpenCodeSessionCreated                  ProductionProof = 200
	ProductionProofOpenCodeToolExecuteBefore               ProductionProof = 201
	ProductionProofOpenCode2SessionPrompt                  ProductionProof = 202
	ProductionProofOpenCode2SessionContext                 ProductionProof = 203
	ProductionProofOpenCode2SessionTitle                   ProductionProof = 204
	ProductionProofOpenCode2SessionModelRequest            ProductionProof = 205
	ProductionProofOpenCode2SessionHttpRequest             ProductionProof = 206
	ProductionProofOpenCode2SessionHttpResponse            ProductionProof = 207
	ProductionProofOpenCode2ToolExecuteBefore              ProductionProof = 208
	ProductionProofOpenCode2ToolExecuteAfter               ProductionProof = 209
	ProductionProofOpenCode2PermissionEvaluate             ProductionProof = 210
	ProductionProofOpenCode2SessionCreated                 ProductionProof = 211
	ProductionProofOpenCode2SessionCompaction              ProductionProof = 212
	ProductionProofOpenCode2SessionGenerate                ProductionProof = 213
	ProductionProofOpenCode2SessionExperimentalWsHandshake ProductionProof = 214
	ProductionProofOpenCode2SessionExperimentalWsSend      ProductionProof = 215
	ProductionProofOpenCode2SessionExperimentalWsReceive   ProductionProof = 216
	ProductionProofOpenCode2SessionRetry                   ProductionProof = 217
)

// openCodeGeneratedProductionProofs lists the generated production proof arms of opencode_targets.go by name, in ordinal order.
var openCodeGeneratedProductionProofs = []namedProductionProof{
	{name: "OpenCodeSessionCreated", proof: ProductionProofOpenCodeSessionCreated},
	{name: "OpenCodeToolExecuteBefore", proof: ProductionProofOpenCodeToolExecuteBefore},
	{name: "OpenCode2SessionPrompt", proof: ProductionProofOpenCode2SessionPrompt},
	{name: "OpenCode2SessionContext", proof: ProductionProofOpenCode2SessionContext},
	{name: "OpenCode2SessionTitle", proof: ProductionProofOpenCode2SessionTitle},
	{name: "OpenCode2SessionModelRequest", proof: ProductionProofOpenCode2SessionModelRequest},
	{name: "OpenCode2SessionHttpRequest", proof: ProductionProofOpenCode2SessionHttpRequest},
	{name: "OpenCode2SessionHttpResponse", proof: ProductionProofOpenCode2SessionHttpResponse},
	{name: "OpenCode2ToolExecuteBefore", proof: ProductionProofOpenCode2ToolExecuteBefore},
	{name: "OpenCode2ToolExecuteAfter", proof: ProductionProofOpenCode2ToolExecuteAfter},
	{name: "OpenCode2PermissionEvaluate", proof: ProductionProofOpenCode2PermissionEvaluate},
	{name: "OpenCode2SessionCreated", proof: ProductionProofOpenCode2SessionCreated},
	{name: "OpenCode2SessionCompaction", proof: ProductionProofOpenCode2SessionCompaction},
	{name: "OpenCode2SessionGenerate", proof: ProductionProofOpenCode2SessionGenerate},
	{name: "OpenCode2SessionExperimentalWsHandshake", proof: ProductionProofOpenCode2SessionExperimentalWsHandshake},
	{name: "OpenCode2SessionExperimentalWsSend", proof: ProductionProofOpenCode2SessionExperimentalWsSend},
	{name: "OpenCode2SessionExperimentalWsReceive", proof: ProductionProofOpenCode2SessionExperimentalWsReceive},
	{name: "OpenCode2SessionRetry", proof: ProductionProofOpenCode2SessionRetry},
}
