// Code generated by "go generate"; DO NOT EDIT.
// Source: the proof declaration tables in opencode_targets.go.

package activation

// OpenCode capture proofs, ordinals 200-299.
const (
	CaptureProofOpenCodeSessionCreated    CaptureProof = 200
	CaptureProofOpenCodeToolExecuteBefore CaptureProof = 201
)

// openCodeGeneratedCaptureProofs lists the generated capture proof arms of opencode_targets.go by name, in ordinal order.
var openCodeGeneratedCaptureProofs = []namedCaptureProof{
	{name: "OpenCodeSessionCreated", proof: CaptureProofOpenCodeSessionCreated},
	{name: "OpenCodeToolExecuteBefore", proof: CaptureProofOpenCodeToolExecuteBefore},
}

// OpenCode production proofs, ordinals 200-299.
const (
	ProductionProofOpenCodeSessionCreated    ProductionProof = 200
	ProductionProofOpenCodeToolExecuteBefore ProductionProof = 201
)

// openCodeGeneratedProductionProofs lists the generated production proof arms of opencode_targets.go by name, in ordinal order.
var openCodeGeneratedProductionProofs = []namedProductionProof{
	{name: "OpenCodeSessionCreated", proof: ProductionProofOpenCodeSessionCreated},
	{name: "OpenCodeToolExecuteBefore", proof: ProductionProofOpenCodeToolExecuteBefore},
}
