// Code generated by "go generate"; DO NOT EDIT.
// Source: the proof declaration tables in claude_targets.go.

package activation

// Claude Code capture proofs, ordinals 1-99.
const (
	CaptureProofSessionStart       CaptureProof = 1
	CaptureProofSessionEnd         CaptureProof = 2
	CaptureProofPreToolUse         CaptureProof = 3
	CaptureProofPostToolUse        CaptureProof = 4
	CaptureProofPostToolUseFailure CaptureProof = 5
	CaptureProofPostToolBatch      CaptureProof = 6
	CaptureProofPreCompact         CaptureProof = 7
	CaptureProofPostCompact        CaptureProof = 8
)

// claudeGeneratedCaptureProofs lists the generated capture proof arms of claude_targets.go by name, in ordinal order.
var claudeGeneratedCaptureProofs = []namedCaptureProof{
	{name: "SessionStart", proof: CaptureProofSessionStart},
	{name: "SessionEnd", proof: CaptureProofSessionEnd},
	{name: "PreToolUse", proof: CaptureProofPreToolUse},
	{name: "PostToolUse", proof: CaptureProofPostToolUse},
	{name: "PostToolUseFailure", proof: CaptureProofPostToolUseFailure},
	{name: "PostToolBatch", proof: CaptureProofPostToolBatch},
	{name: "PreCompact", proof: CaptureProofPreCompact},
	{name: "PostCompact", proof: CaptureProofPostCompact},
}

// Claude Code production proofs, ordinals 1-99.
const (
	ProductionProofSessionStart       ProductionProof = 1
	ProductionProofSessionEnd         ProductionProof = 2
	ProductionProofPreToolUse         ProductionProof = 3
	ProductionProofPostToolUse        ProductionProof = 4
	ProductionProofPostToolUseFailure ProductionProof = 5
	ProductionProofPostToolBatch      ProductionProof = 6
	ProductionProofPreCompact         ProductionProof = 7
	ProductionProofPostCompact        ProductionProof = 8
)

// claudeGeneratedProductionProofs lists the generated production proof arms of claude_targets.go by name, in ordinal order.
var claudeGeneratedProductionProofs = []namedProductionProof{
	{name: "SessionStart", proof: ProductionProofSessionStart},
	{name: "SessionEnd", proof: ProductionProofSessionEnd},
	{name: "PreToolUse", proof: ProductionProofPreToolUse},
	{name: "PostToolUse", proof: ProductionProofPostToolUse},
	{name: "PostToolUseFailure", proof: ProductionProofPostToolUseFailure},
	{name: "PostToolBatch", proof: ProductionProofPostToolBatch},
	{name: "PreCompact", proof: ProductionProofPreCompact},
	{name: "PostCompact", proof: ProductionProofPostCompact},
}
