// Code generated by "go generate"; DO NOT EDIT.
// Source: the proof declaration tables in codex_targets.go.

package activation

// Codex capture proofs, ordinals 100-199.
const (
	CaptureProofCodexSessionStart CaptureProof = 100
	CaptureProofCodexPreToolUse   CaptureProof = 101
)

// codexGeneratedCaptureProofs lists the generated capture proof arms of codex_targets.go by name, in ordinal order.
var codexGeneratedCaptureProofs = []namedCaptureProof{
	{name: "CodexSessionStart", proof: CaptureProofCodexSessionStart},
	{name: "CodexPreToolUse", proof: CaptureProofCodexPreToolUse},
}

// Codex production proofs, ordinals 100-199.
const (
	ProductionProofCodexSessionStart ProductionProof = 100
	ProductionProofCodexPreToolUse   ProductionProof = 101
)

// codexGeneratedProductionProofs lists the generated production proof arms of codex_targets.go by name, in ordinal order.
var codexGeneratedProductionProofs = []namedProductionProof{
	{name: "CodexSessionStart", proof: ProductionProofCodexSessionStart},
	{name: "CodexPreToolUse", proof: ProductionProofCodexPreToolUse},
}
