//go:build ignore

// Command gen writes metamodel.gen.go from the pinned runtime lifecycle profiles.
// It is invoked by `go generate ./internal/lifecycle/metamodel/...` (wired into
// `make generate`). The output is deterministic, so a second run is zero-diff.
package main

import (
	"fmt"
	"go/format"
	"os"

	"github.com/dayvidpham/pasture/internal/lifecycle/metamodel"
)

func main() {
	body, err := metamodel.GenerateLifecycleMetamodel()
	if err != nil {
		fmt.Fprintf(os.Stderr, "metamodel generate: build canonical body: %v\n", err)
		os.Exit(1)
	}
	source := fmt.Sprintf(`// Code generated by "go generate"; DO NOT EDIT.
// Source: the pinned runtime lifecycle profiles (internal/runtime).

package metamodel

// lifecycleMetamodel is the content-addressed lifecycle interpretation vocabulary
// derived from the pinned runtime lifecycle profiles. Its sha256 is the active
// lifecycle metamodel manifest's content identity.
var lifecycleMetamodel = []byte(%q)
`, body)
	formatted, err := format.Source([]byte(source))
	if err != nil {
		fmt.Fprintf(os.Stderr, "metamodel generate: gofmt generated source: %v\n", err)
		os.Exit(1)
	}
	if err := os.WriteFile("metamodel.gen.go", formatted, 0o644); err != nil {
		fmt.Fprintf(os.Stderr, "metamodel generate: write metamodel.gen.go: %v\n", err)
		os.Exit(1)
	}
}
