// Code generated by hostcontractgen. DO NOT EDIT.
package codex

import (
	"github.com/dayvidpham/pasture/internal/lifecycle/model"
	"github.com/dayvidpham/pasture/internal/lifecycle/registration"
)

var fieldNames = map[model.NativeFieldID]string{
	registration.FieldCodexSessionID: "session_id",
	registration.FieldCodexTurnID:    "turn_id",
	registration.FieldCodexToolUseID: "tool_use_id",
}
