// Code generated by codegen. DO NOT EDIT.
package inventory

import "github.com/dayvidpham/pasture/internal/codegen/ir"

func init() {
	nativeFunctionRows = []Row{
		{Key{Harness: ir.HarnessOpenCode, Kind: KindNativeFunction, ID: "question"}},
		{Key{Harness: ir.HarnessOpenCode, Kind: KindNativeFunction, ID: "skill"}},
		{Key{Harness: ir.HarnessOpenCode, Kind: KindNativeFunction, ID: "task"}},
		{Key{Harness: ir.HarnessCodex, Kind: KindNativeFunction, ID: "request-input"}},
	}
}
