// Code generated by hostcontractgen. DO NOT EDIT.
package opencode

import (
	"github.com/dayvidpham/pasture/internal/lifecycle/model"
	"github.com/dayvidpham/pasture/internal/lifecycle/registration"
)

var fieldNames2_0_20 = map[model.NativeFieldID]string{
	registration.FieldOpenCode2SessionID: "sessionID",
	registration.FieldOpenCode2CallID:    "id",
}
