// Code generated by hostcontractgen. DO NOT EDIT.
package opencode

import (
	"github.com/dayvidpham/pasture/internal/lifecycle/model"
	"github.com/dayvidpham/pasture/internal/lifecycle/registration"
)

var fieldNames = map[model.NativeFieldID]string{
	registration.FieldOpenCodeSessionID: "sessionID",
	registration.FieldOpenCodeCallID:    "callID",
}
