// Code generated by Pasture for OpenCode. DO NOT EDIT.
// Runtime contract: __PASTURE_CONTRACT_COMMENT__
// This plugin performs no runtime imports and requires only Bun plus the built pasture binary.

export const PASTURE_NATIVE_TOOLS = Object.freeze([/* PASTURE_NATIVE_TOOLS */]);
export const PASTURE_RUNTIME_CONTRACT = "__PASTURE_CONTRACT_LITERAL__";
const METADATA = /* PASTURE_METADATA */ {};
type LifecycleResponse =
  | { decision: "proceed" }
  | { decision: "deny"; reason: string };

const CHILD_WAIT_MS = 8000;
const CONFIGURATION_ADVICE = "; verify PASTURE_BIN and the generated OpenCode __PASTURE_HOST_VERSION__ configuration";

async function forwardDiagnostic(stderr: string, event: string): Promise<void> {
  const sink = process.stderr;
  try {
    await new Promise<void>((resolve, reject) => {
      let settled = false;
      const finish = (error?: Error | null) => {
        if (settled) return;
        settled = true;
        // Writable calls its write callback BEFORE emitting the error event.
        // Keep the listener through that turn, then remove both listeners.
        setImmediate(() => {
          sink.off("error", onError);
          sink.off("close", onClose);
          if (error) reject(error);
          else resolve();
        });
      };
      const onError = (error: Error) => finish(error);
      const onClose = () => finish(new Error("standard error closed before the diagnostic was written"));
      sink.on("error", onError);
      sink.on("close", onClose);
      if (sink.destroyed || sink.closed || sink.writableEnded) {
        finish(new Error("standard error is not writable"));
        return;
      }
      try {
        // One write, no further chunks while backpressured. The callback means
        // the entire chunk was handled, even when write() returned false.
        sink.write(stderr, "utf8", finish);
      } catch (error) {
        finish(error instanceof Error ? error : new Error(String(error)));
      }
    });
  } catch (error) {
    throw new Error("pasture hook lifecycle diagnostic forwarding for " + event + " failed: " + error + "; restore the OpenCode standard-error sink and retry" + CONFIGURATION_ADVICE);
  }
}

async function drain(reader: ReadableStreamDefaultReader<Uint8Array>): Promise<string> {
  const decoder = new TextDecoder();
  let text = "";
  while (true) {
    const { done, value } = await reader.read();
    if (done) return text + decoder.decode();
    text += decoder.decode(value, { stream: true });
  }
}

// The running host reports its own release on the setup context as
// ctx.app.version (packages/plugin/src/app.ts: App.version, exposed on the
// promise Context at packages/plugin/src/promise/plugin.ts). setup captures
// it once below; every helper runs outside setup's scope, so the captured
// flags wait here. Empty means absent: no version is ever invented, and an
// absent version leaves each command unflagged for the binary to resolve.
// setup assigns on every run, so a setup without a usable version clears a
// previous capture instead of reusing it.
let pastureHostVersionArgs = [];

// A host self-report is carried only when it is release-shaped: an optional
// leading "v", a MAJOR.MINOR.PATCH triple, and optional suffix metadata. The
// running host reports "local" for source builds and "unknown" when its
// metadata is unconfigured, and neither is a release: forwarding one would
// bypass the version probe with a value the binary cannot route, silently
// selecting the oldest contract row for a newer host's payloads. This is a
// coarse pre-filter, not the authority — the binary still parses strictly and
// faults honestly on anything it cannot admit. Anything not release-shaped is
// cleared so the probe resolves.
function pastureReleaseShaped(value) {
  return typeof value === "string" && /^v?\d+\.\d+\.\d+(?:[-+].*)?$/.test(value.trim());
}

async function invokeLifecycle(command, event, value) {
  const binary = process.env.__PASTURE_BINARY_ENV__ ?? "pasture";
  // Carry the setup-observed host version unless this invocation already
  // names its own (the session.created observation does, from its bus data).
  // Both sources are release-shape-gated where captured, so an unflagged
  // command means no usable report existed and the binary resolves the
  // version itself. A later host stays admissible: the binary admits its
  // recorded baseline and every later release, so forwarding the running
  // release never narrows it.
  const effective = command.includes("--host-version") || pastureHostVersionArgs.length === 0 ? command : [...command, ...pastureHostVersionArgs];
  const child = Bun.spawn({
    cmd: [binary, ...effective],
    stdin: new Blob([JSON.stringify(value)]),
    stdout: "pipe",
    stderr: "pipe",
  });
  const stdoutReader = child.stdout.getReader();
  const stderrReader = child.stderr.getReader();
  let timer: ReturnType<typeof setTimeout> | undefined;
  let timedOut = false;
  let result: [string, string, number];
  try {
    // This outer bound includes BOTH pipe drains and exit. It sits above the
    // binary's 5s cancellation budget; it is not a measured universal host limit.
    // Killing the process can interrupt settlement after cancellation. This
    // outer bound cannot promise delivery of a committed response afterward.
    result = await Promise.race([
      Promise.all([drain(stdoutReader), drain(stderrReader), child.exited]),
      new Promise<never>((_, reject) => {
        timer = setTimeout(() => {
          timedOut = true;
          child.kill("SIGKILL");
          reject(new Error("timed out after " + CHILD_WAIT_MS + " ms"));
        }, CHILD_WAIT_MS);
      }),
    ]);
  } catch (error) {
    if (!timedOut && child.exitCode === null) child.kill("SIGKILL");
    // Cancel pending reads as well: inherited pipes can remain open even after
    // the direct child exits. Always wait for the direct child to be reaped.
    await Promise.allSettled([stdoutReader.cancel(), stderrReader.cancel(), child.exited]);
    throw new Error("pasture hook lifecycle for " + event + " " + (error instanceof Error ? error.message : String(error)) + CONFIGURATION_ADVICE);
  } finally {
    clearTimeout(timer);
    stdoutReader.releaseLock();
    stderrReader.releaseLock();
  }
  const [stdout, stderr, exitCode] = result;
  if (exitCode !== 0) throw new Error("pasture hook lifecycle for " + event + " exited " + exitCode + ": " + (stderr.trim() || "no diagnostic was returned") + CONFIGURATION_ADVICE);
  // fd 2 is piped, not inherited. Preserve the child's diagnostic and the
  // existing terminal-newline policy without console.error decoration.
  // Bun.write(Bun.stderr, ...) stalled after a partial write in the generated
  // plugin's spawned-child/pipe context under Bun 1.3.13. Writable completion
  // is exercised in that same context; Bun's internal cause is not established.
  if (stderr.trim() !== "") {
    // A successful lifecycle decision must survive a host that has closed or
    // rejected its diagnostic stream. The child's stdout remains authoritative.
    await forwardDiagnostic(stderr.endsWith("\n") ? stderr : stderr + "\n", event).catch(() => {});
  }
  return stdout;
}

function parseResponse(stdout: string, event: string): LifecycleResponse | undefined {
  // An EMPTY body at exit 0 means pasture could not evaluate the event and let
  // this host continue. It is not a decision and it is not a fault of this
  // callback, so the callback continues and reports on the console. This belt
  // exists so that an OLD pasture binary, which emitted nothing on a fail-open
  // fault, still cannot abort the user's action.
  //
  // THE CONSOLE LINE SENDS THE OPERATOR TO STANDARD ERROR AND ONLY OFFERS THE
  // RECORD. It used to promise both unconditionally. Standard error is where
  // pasture reports every such fault, and it is also where it reports that it
  // could not write a record at all; the durable line is the thing that may be
  // missing, because a fault whose record cannot be placed or written leaves
  // none. The old wording sent an operator who had just lost a gate evaluation
  // to hunt for a file that is not there on exactly the routes it fires on.
  //
  // THE STREAM IT NAMES IS ATTEMPTED, NOT GUARANTEED. invokeLifecycle forwards
  // the child's diagnostic best effort: a healthy sink receives it, while a
  // sink the host has closed or that rejects the write neither fails the hook
  // nor delivers the bytes. For one round this line named standard error while
  // the spawn above piped fd 2 and dropped everything it caught on the exit-0
  // route, so the operator was sent to a stream this callback had emptied.
  // Evidence named to a reader who cannot reach it is the same defect as
  // evidence that does not exist; best-effort forwarding must therefore say so
  // rather than promise delivery.
  if (stdout.trim() === "") {
    console.error("Pasture did not evaluate " + event + " and returned no decision; the host continues unevaluated. Read the pasture diagnostic on standard error first: pasture writes every such fault there, including the case where it could not write a durable record, and this plugin forwards it there best effort — so it may be missing when the host has closed that stream. A line may also have been appended to lifecycle-faults.jsonl beside the pasture database, but a fault whose record could not be placed or written leaves none, and the diagnostic then quotes the path it tried.");
    return;
  }
  let response: unknown;
  try {
    response = JSON.parse(stdout);
  } catch (error) {
    throw new Error("pasture hook lifecycle response is not JSON for " + event + ": " + error + CONFIGURATION_ADVICE);
  }
  if (response !== null && typeof response === "object" && !Array.isArray(response)) {
    const record = response as Record<string, unknown>;
    const keys = Object.keys(record);
    if (keys.length === 1 && record.decision === "proceed") {
      return { decision: "proceed" };
    }
    if (keys.length === 2 && record.decision === "deny" &&
        typeof record.reason === "string" && record.reason.length > 0) {
      return { decision: "deny", reason: record.reason };
    }
  }
  throw new Error('pasture hook lifecycle response must be exactly {"decision":"proceed"} or {"decision":"deny","reason":<nonempty string>} for ' + event + CONFIGURATION_ADVICE);
}

/* PASTURE_HELPERS */
export default {
  id: "pasture-lifecycle",
  setup: async (ctx) => {
/* PASTURE_SETUP */  },
};
