package proofgen_test

import (
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strings"
	"testing"

	"github.com/stretchr/testify/require"

	"github.com/dayvidpham/pasture/internal/lifecycle/activation/internal/proofgen"
)

// row is one declared arm for a synthetic target file.
type row struct {
	ordinal int
	arm     string
}

// harnessFile renders a minimal target file with the two tables the generator
// reads, in the shape the real target files use.
func harnessFile(capture, production []row) string {
	var b strings.Builder
	b.WriteString("package activation\n\n")
	b.WriteString("var xCaptureProofs = [...]captureProofDeclaration{\n")
	for _, r := range capture {
		fmt.Fprintf(&b, "\t{ordinal: %d, arm: %q, event: 1, fixture: \"f\"},\n", r.ordinal, r.arm)
	}
	b.WriteString("}\n\nvar xProductionProofs = [...]productionProofDeclaration{\n")
	for _, r := range production {
		fmt.Fprintf(&b, "\t{ordinal: %d, arm: %q, event: 1, test: \"t\"},\n", r.ordinal, r.arm)
	}
	b.WriteString("}\n")
	return b.String()
}

// writeTree writes one synthetic target file per harness into a temp dir and
// returns the dir. A harness the caller does not supply gets one in-range arm
// of each kind, because a file with no arm of a kind is refused.
func writeTree(t *testing.T, files map[string]string) string {
	t.Helper()
	dir := t.TempDir()
	for _, harness := range proofgen.Harnesses {
		body, ok := files[harness.TargetFile]
		if !ok {
			filler := []row{{harness.Low, "Filler" + strings.ReplaceAll(harness.Label, " ", "")}}
			body = harnessFile(filler, filler)
		}
		require.NoError(t, os.WriteFile(filepath.Join(dir, harness.TargetFile), []byte(body), 0o600))
	}
	return dir
}

func TestGenerateEmitsOneConstantPerArmInsideItsHarnessRange(t *testing.T) {
	t.Parallel()
	dir := writeTree(t, map[string]string{
		"claude_targets.go":   harnessFile([]row{{1, "SessionStart"}, {2, "SessionEnd"}}, []row{{1, "SessionStart"}}),
		"codex_targets.go":    harnessFile([]row{{100, "CodexSessionStart"}}, []row{{100, "CodexSessionStart"}}),
		"opencode_targets.go": harnessFile([]row{{200, "OpenCodeSessionCreated"}}, []row{{200, "OpenCodeSessionCreated"}}),
	})
	files, err := proofgen.Generate(dir)
	require.NoError(t, err)
	require.Len(t, files, 3)
	claude := string(files["proofs_claude.gen.go"])
	requireConstant(t, claude, "CaptureProofSessionStart", "CaptureProof", 1)
	requireConstant(t, claude, "CaptureProofSessionEnd", "CaptureProof", 2)
	requireConstant(t, claude, "ProductionProofSessionStart", "ProductionProof", 1)
	require.Contains(t, claude, `{name: "SessionStart", proof: CaptureProofSessionStart}`)
	require.Contains(t, claude, "// Code generated by \"go generate\"; DO NOT EDIT.")
	codex := string(files["proofs_codex.gen.go"])
	requireConstant(t, codex, "CaptureProofCodexSessionStart", "CaptureProof", 100)
	openCode := string(files["proofs_opencode.gen.go"])
	requireConstant(t, openCode, "CaptureProofOpenCodeSessionCreated", "CaptureProof", 200)
	requireConstant(t, openCode, "ProductionProofOpenCodeSessionCreated", "ProductionProof", 200)

	again, err := proofgen.Generate(dir)
	require.NoError(t, err)
	require.Equal(t, files, again, "generation is deterministic")
}

func TestGenerateRefusesADuplicateOrdinalAcrossTwoHarnessFilesNamingBothArms(t *testing.T) {
	t.Parallel()
	dir := writeTree(t, map[string]string{
		"claude_targets.go": harnessFile([]row{{1, "SessionStart"}}, []row{{1, "SessionStart"}}),
		"codex_targets.go":  harnessFile([]row{{1, "CodexSessionStart"}}, []row{{100, "CodexSessionStart"}}),
	})
	// Two files cannot share an in-range ordinal because the ranges are
	// disjoint, so a cross-file duplicate is always also a range violation and
	// the range refusal fires first. The collision refusal is exercised inside
	// one file below.
	_, err := proofgen.Generate(dir)
	require.ErrorContains(t, err, `outside the Codex range 100-199`)

	dir = writeTree(t, map[string]string{
		"claude_targets.go": harnessFile([]row{{7, "PreCompact"}, {7, "PostCompact"}}, []row{{7, "PreCompact"}}),
	})
	_, err = proofgen.Generate(dir)
	require.ErrorContains(t, err, `capture proof ordinal 7 is declared twice`)
	require.ErrorContains(t, err, `arm "PreCompact" in claude_targets.go`)
	require.ErrorContains(t, err, `arm "PostCompact" in claude_targets.go`)

	// Production ordinals are a separate space: the same ordinal in the
	// capture table and the production table is not a collision.
	dir = writeTree(t, map[string]string{
		"claude_targets.go": harnessFile([]row{{7, "PreCompact"}}, []row{{7, "PreCompact"}}),
	})
	_, err = proofgen.Generate(dir)
	require.NoError(t, err)
}

func TestGenerateRefusesAnArmOutsideItsHarnessRangeNamingTheArm(t *testing.T) {
	t.Parallel()
	for name, tc := range map[string]struct {
		file string
		rows []row
		want string
	}{
		"codex-arm-with-a-claude-ordinal":      {"codex_targets.go", []row{{5, "CodexSessionStart"}}, `capture proof arm "CodexSessionStart" in codex_targets.go has ordinal 5 outside the Codex range 100-199`},
		"claude-arm-above-its-range":           {"claude_targets.go", []row{{100, "SessionStart"}}, `capture proof arm "SessionStart" in claude_targets.go has ordinal 100 outside the Claude Code range 1-99`},
		"opencode-arm-below-its-range":         {"opencode_targets.go", []row{{199, "OpenCodeSessionCreated"}}, `outside the OpenCode range 200-299`},
		"opencode-arm-above-its-range":         {"opencode_targets.go", []row{{300, "OpenCodeSessionCreated"}}, `outside the OpenCode range 200-299`},
		"ordinal-zero-is-the-invalid-zero-arm": {"claude_targets.go", []row{{0, "SessionStart"}}, `has ordinal 0, which is reserved for the invalid zero value`},
	} {
		name, tc := name, tc
		t.Run(name, func(t *testing.T) {
			t.Parallel()
			dir := writeTree(t, map[string]string{tc.file: harnessFile(tc.rows, tc.rows)})
			_, err := proofgen.Generate(dir)
			require.ErrorContains(t, err, tc.want)
		})
	}
}

func TestGenerateRefusesADuplicateArmNameAcrossFiles(t *testing.T) {
	t.Parallel()
	dir := writeTree(t, map[string]string{
		"claude_targets.go": harnessFile([]row{{1, "SessionStart"}}, []row{{1, "SessionStart"}}),
		"codex_targets.go":  harnessFile([]row{{100, "SessionStart"}}, []row{{100, "CodexSessionStart"}}),
	})
	_, err := proofgen.Generate(dir)
	require.ErrorContains(t, err, `capture proof arm "SessionStart" is declared twice: in claude_targets.go and in codex_targets.go`)
}

func TestParseRefusesRowsTheGeneratorCannotRead(t *testing.T) {
	t.Parallel()
	for name, tc := range map[string]struct{ body, want string }{
		"ordinal-is-an-expression": {
			"package activation\nvar a = [...]captureProofDeclaration{{ordinal: 1 + 1, arm: \"X\"}}\nvar b = [...]productionProofDeclaration{}\n",
			"must be an integer literal"},
		"ordinal-is-a-named-constant": {
			"package activation\nvar a = [...]captureProofDeclaration{{ordinal: first, arm: \"X\"}}\nvar b = [...]productionProofDeclaration{}\n",
			"must be an integer literal"},
		"arm-is-not-a-string-literal": {
			"package activation\nvar a = [...]captureProofDeclaration{{ordinal: 1, arm: name}}\nvar b = [...]productionProofDeclaration{}\n",
			"must be a string literal"},
		"arm-is-not-an-exported-identifier": {
			"package activation\nvar a = [...]captureProofDeclaration{{ordinal: 1, arm: \"session start\"}}\nvar b = [...]productionProofDeclaration{}\n",
			"must be an exported Go identifier fragment"},
		"row-without-an-ordinal": {
			"package activation\nvar a = [...]captureProofDeclaration{{arm: \"X\"}}\nvar b = [...]productionProofDeclaration{}\n",
			"needs both an ordinal and an arm name"},
		"positional-row": {
			"package activation\nvar a = [...]captureProofDeclaration{{1, \"X\", 1, \"f\"}}\nvar b = [...]productionProofDeclaration{}\n",
			"must use keyed fields"},
		"missing-production-table": {
			"package activation\nvar a = [...]captureProofDeclaration{}\n",
			"declares no production proof table"},
		"missing-capture-table": {
			"package activation\nvar b = [...]productionProofDeclaration{}\n",
			"declares no capture proof table"},
		"two-capture-tables": {
			"package activation\nvar a = [...]captureProofDeclaration{}\nvar c = [...]captureProofDeclaration{}\nvar b = [...]productionProofDeclaration{}\n",
			"declares two capture proof tables"},
	} {
		name, tc := name, tc
		t.Run(name, func(t *testing.T) {
			t.Parallel()
			path := filepath.Join(t.TempDir(), "claude_targets.go")
			require.NoError(t, os.WriteFile(path, []byte(tc.body), 0o600))
			_, err := proofgen.Parse(path)
			require.ErrorContains(t, err, tc.want)
		})
	}
}

// TestGenerateRefusesAHarnessFileWithNoArmOfAKind is the control against a
// silent empty generation: a file whose tables the walk cannot read, or that
// is empty, must stop generation instead of emitting empty proof files that
// every range assertion would pass over.
func TestGenerateRefusesAHarnessFileWithNoArmOfAKind(t *testing.T) {
	t.Parallel()
	for name, body := range map[string]string{
		"both-tables-empty":         harnessFile(nil, nil),
		"production-table-empty":    harnessFile([]row{{100, "CodexSessionStart"}}, nil),
		"capture-table-empty":       harnessFile(nil, []row{{100, "CodexSessionStart"}}),
		"tables-under-another-type": strings.ReplaceAll(strings.ReplaceAll(harnessFile([]row{{100, "CodexSessionStart"}}, []row{{100, "CodexSessionStart"}}), "captureProofDeclaration", "captureProofRow"), "productionProofDeclaration", "productionProofRow"),
	} {
		name, body := name, body
		t.Run(name, func(t *testing.T) {
			t.Parallel()
			dir := writeTree(t, map[string]string{"codex_targets.go": body})
			_, err := proofgen.Generate(dir)
			require.Error(t, err)
			require.Regexp(t, `codex_targets.go declares no (capture|production) proof (arm at all|table)`, err.Error())
		})
	}
}

// TestCommittedProofFilesMatchTheGenerator is the in-package drift gate: the
// three committed generated files must equal a fresh generation from the
// committed target files, so a hand edit to either side turns RED here as
// well as in the repository-wide generate gate.
func TestCommittedProofFilesMatchTheGenerator(t *testing.T) {
	t.Parallel()
	dir := filepath.Join("..", "..")
	files, err := proofgen.Generate(dir)
	require.NoError(t, err)
	for _, harness := range proofgen.Harnesses {
		committed, err := os.ReadFile(filepath.Join(dir, harness.Output))
		require.NoError(t, err, "the committed %s must exist; run make generate", harness.Output)
		require.Equal(t, string(files[harness.Output]), string(committed),
			"%s drifted from the proof declaration tables in %s; run make generate and commit the result", harness.Output, harness.TargetFile)
	}
}

// TestHarnessRangesAreDisjointAndExcludeZero pins the partition the generator
// enforces: three ranges, no overlap, none containing the invalid zero.
func TestHarnessRangesAreDisjointAndExcludeZero(t *testing.T) {
	t.Parallel()
	require.Len(t, proofgen.Harnesses, 3)
	for i, a := range proofgen.Harnesses {
		require.Greater(t, a.Low, 0, "%s range must exclude ordinal 0", a.Label)
		require.LessOrEqual(t, a.Low, a.High)
		for _, b := range proofgen.Harnesses[i+1:] {
			require.True(t, a.High < b.Low || b.High < a.Low, "%s range %d-%d overlaps %s range %d-%d", a.Label, a.Low, a.High, b.Label, b.Low, b.High)
		}
	}
}

// requireConstant asserts one generated constant with its type and ordinal,
// tolerant of the column alignment gofmt applies inside a const block.
func requireConstant(t *testing.T, source, name, enum string, ordinal int) {
	t.Helper()
	pattern := regexp.MustCompile(`(?m)^\t` + regexp.QuoteMeta(name) + `\s+` + enum + ` = ` + fmt.Sprint(ordinal) + `$`)
	require.Regexp(t, pattern, source, "generated source must declare %s %s = %d", name, enum, ordinal)
}
