package main

import (
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"

	"github.com/stretchr/testify/require"
)

// openCodePluginStubSource is the exact stub of the host-provided
// "@opencode/plugin" specifier every Bun proof writes beside the module under
// test. It mirrors the host's own define, which is the identity function, so
// the shape under test is the module's, not the SDK's. The stub keeps proofs
// hermetic: without it Bun resolves the ambient install cache, and a proof
// would pass or fail on machine state instead of the generated bytes. The
// same bytes are pinned in internal/codegen's transport proofs; both pins
// must name the identity define.
const openCodePluginStubSource = "export const Plugin = { define: (plugin) => plugin };\n"

func writeOpenCodePluginStubFiles(t *testing.T, dir string) {
	t.Helper()
	stubDir := filepath.Join(dir, "node_modules", "@opencode", "plugin")
	require.NoError(t, os.MkdirAll(stubDir, 0o755))
	require.NoError(t, os.WriteFile(filepath.Join(stubDir, "package.json"), []byte(`{"name":"@opencode/plugin","type":"module","main":"index.js"}`+"\n"), 0o644))
	require.NoError(t, os.WriteFile(filepath.Join(stubDir, "index.js"), []byte(openCodePluginStubSource), 0o644))
}

// TestOpenCodePluginStubMirrorsHostDefine pins the stub every Bun proof
// depends on and proves the pin load-bearing by mutation: the stub's
// load-bearing property is that define returns its argument, so a mutant
// define that drops the plugin must fail the host loader rule the proofs
// assume.
//
// WHAT IT VISITS: the stub bytes shared by the Bun proofs in this package.
// WHAT IT DOES NOT READ: the host SDK source the stub mirrors; that binding
// is stated by citation, not derived, and a host change to define is caught
// at the next host re-pin, not here.
func TestOpenCodePluginStubMirrorsHostDefine(t *testing.T) {
	t.Parallel()
	require.Contains(t, openCodePluginStubSource, "define: (plugin) => plugin",
		"the plugin stub must mirror the host identity define: it returns its argument")
	bun, err := exec.LookPath("bun")
	require.NoError(t, err, "bun is required to pin the plugin stub")
	dir := t.TempDir()
	writeOpenCodePluginStubFiles(t, dir)
	// What the pin holds is the identity semantics the loader-rule proofs
	// assume. Prove it by running the define through both the pinned and a
	// mutant stub.
	for _, tc := range []struct {
		name    string
		define  string
		wantOut string
		wantErr string
	}{
		{name: "identity", define: openCodePluginStubSource, wantOut: "pasture-lifecycle"},
		{name: "non-identity mutant breaks the shape", define: "export const Plugin = { define: () => ({}) };\n", wantErr: "non-empty string id"},
	} {
		t.Run(tc.name, func(t *testing.T) {
			work := t.TempDir()
			stubDir := filepath.Join(work, "node_modules", "@opencode", "plugin")
			require.NoError(t, os.MkdirAll(stubDir, 0o755))
			require.NoError(t, os.WriteFile(filepath.Join(stubDir, "package.json"), []byte(`{"name":"@opencode/plugin","type":"module","main":"index.js"}`+"\n"), 0o644))
			require.NoError(t, os.WriteFile(filepath.Join(stubDir, "index.js"), []byte(tc.define), 0o644))
			probe := filepath.Join(work, "pin.ts")
			require.NoError(t, os.WriteFile(probe, []byte(`
import { Plugin } from "@opencode/plugin";
const value = Plugin.define({ id: "pasture-lifecycle", setup: async () => {} });
if (typeof value.id !== "string" || value.id.trim() === "") throw new Error("non-empty string id");
console.log(value.id);
`), 0o600))
			out, err := exec.Command(bun, probe).CombinedOutput()
			if tc.wantErr == "" {
				require.NoError(t, err, string(out))
				require.Contains(t, strings.TrimSpace(string(out)), tc.wantOut)
				return
			}
			require.Error(t, err, "the mutant stub must break the plugin shape")
			require.Contains(t, string(out), tc.wantErr)
		})
	}
}
